In [9]:
import glob
import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm

In [2]:
# Download associaiton file
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results/regenie_127phenotypes_lofteeHC_mac20.parquet -o /home/dnanexus/data_dir/
# !dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results/loftee_mac20_associations_bh_corrected.parquet -o /home/dnanexus/data_dir/

bt = pl.read_parquet('/home/dnanexus/data_dir/regenie_127phenotypes_lofteeHC_mac20.parquet')
bt = bt.filter(pl.col('pval_fdr')<=0.05)
bt

dxpy.utils.resolver.ResolutionError: Unable to resolve "regenie_127phenotypes_lofteeHC_mac20.parquet" to a data object or folder name in '/processed_data/REGENIE_results'

shape: (2_289, 21)
┌────────────┬─────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ region     ┆ chr ┆ phenotype  ┆ cohort     ┆ … ┆ controls_a ┆ info       ┆ pval_fdr  ┆ pval_bonf │
│ ---        ┆ --- ┆ ---        ┆ ---        ┆   ┆ lt         ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆ i64 ┆ str        ┆ str        ┆   ┆ ---        ┆ str        ┆ f64       ┆ f64       │
│            ┆     ┆            ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞════════════╪═════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ ENSG000001 ┆ 1   ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.000007  ┆ 0.003328  │
│ 32855      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.076632; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=128.00 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000000 ┆ 11  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.038502  ┆ 1.0       │
│ 52841      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.196317; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=38.000 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 11  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.003376  ┆ 1.0       │
│ 10243      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.094032; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=85.001 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 11  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 4.5099e-4 ┆ 1.3530e-4 │
│ 18137      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.173370; ┆ 6         ┆ 4         │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=25.000 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 12  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.006545  ┆ 1.0       │
│ 73064      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.189177; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=41.000 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ …          ┆ …   ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ ENSG000001 ┆ 7   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.02095   ┆ 1.0       │
│ 82095      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.200004; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=24.500 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 8   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.036208  ┆ 1.0       │
│ 64741      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.155565; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=40.500 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000002 ┆ 8   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.045581  ┆ 1.0       │
│ 05189      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.156523; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=20.000 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 9   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.027724  ┆ 1.0       │
│ 82752      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.161667; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=36.500 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000000 ┆ 9   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.045758  ┆ 1.0       │
│ 56586      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.129988; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=29.000 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
└────────────┴─────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [3]:
# Download annotation file for variant-gene mapping
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/annotations_fill_na.parquet -o /home/dnanexus/data_dir/

anno = pl.read_parquet(
    '/home/dnanexus/data_dir/annotations_fill_na.parquet', 
    columns=['id', 'region']
)

anno

Error: path "/home/dnanexus/data_dir/annotations_fill_na.parquet" already
exists but -f/--overwrite was not set

shape: (74_534_850, 2)
┌─────────────────────┬─────────────────┐
│ id                  ┆ region          │
│ ---                 ┆ ---             │
│ str                 ┆ str             │
╞═════════════════════╪═════════════════╡
│ chr18:56603287:T:G  ┆ ENSG00000091164 │
│ chr18:56611517:A:G  ┆ ENSG00000091164 │
│ chr19:34340475:G:A  ┆ ENSG00000166398 │
│ chr19:5256210:T:C   ┆ ENSG00000105426 │
│ chr19:5257316:G:C   ┆ ENSG00000105426 │
│ …                   ┆ …               │
│ chr16:179290:T:A    ┆ ENSG00000086506 │
│ chr7:148348869:A:G  ┆ ENSG00000174469 │
│ chr5:138680487:A:G  ┆ ENSG00000044115 │
│ chr4:70839545:A:G   ┆ ENSG00000132463 │
│ chr15:72103067:A:AC ┆ ENSG00000066933 │
└─────────────────────┴─────────────────┘

In [4]:
anno_pheno = (
    anno.join(
        bt.select(['region', 'phenotype']).unique(), 
        on='region', 
        how='inner'
    )
)

anno_pheno

shape: (75_468_554, 3)
┌─────────────────────┬─────────────────┬─────────────────────────────────┐
│ id                  ┆ region          ┆ phenotype                       │
│ ---                 ┆ ---             ┆ ---                             │
│ str                 ┆ str             ┆ str                             │
╞═════════════════════╪═════════════════╪═════════════════════════════════╡
│ chr19:34340475:G:A  ┆ ENSG00000166398 ┆ seated_height_int               │
│ chr19:34340475:G:A  ┆ ENSG00000166398 ┆ sitting_height_int              │
│ chr2:215390704:C:T  ┆ ENSG00000115414 ┆ forced_expiratory_volume_in_1s… │
│ chr2:178702309:A:G  ┆ ENSG00000155657 ┆ arm_fatfree_mass_left_int       │
│ chr2:178702309:A:G  ┆ ENSG00000155657 ┆ pulse_rate_automated_reading_i… │
│ …                   ┆ …               ┆ …                               │
│ chr15:72103059:G:GC ┆ ENSG00000066933 ┆ sitting_height_int              │
│ chr17:64662044:G:C  ┆ ENSG00000108854 ┆ forced_vital_capacity_fvc_int   │
│ chr17:64662044:G:C  ┆ ENSG00000108854 ┆ standing_height_int             │
│ chr2:158525435:T:C  ┆ ENSG00000144283 ┆ hip_circumference_int           │
│ chr15:72103067:A:AC ┆ ENSG00000066933 ┆ sitting_height_int              │
└─────────────────────┴─────────────────┴─────────────────────────────────┘

In [5]:
# Download phenotypes: covariates and PRS corrected
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/phenotypes/corrected_cov_PRS_traits_EUR.parquet -o /home/dnanexus/data_dir/

phenos = (
    pl.read_parquet('/home/dnanexus/data_dir/corrected_cov_PRS_traits_EUR.parquet')
    .select(['individual'] + bt['phenotype'].unique().to_list())
    .rename({'individual':'sample'})
)

# phenos

long_phenos = (
    phenos
    .unpivot(
        index='sample',
        on=bt['phenotype'].unique().to_list(),
        variable_name='phenotype',
        value_name='pheno_value'
    )
    .drop_nulls()
)

print(long_phenos['phenotype'].value_counts(sort=True))
long_phenos

Error: path "/home/dnanexus/data_dir/corrected_cov_PRS_traits_EUR.parquet"
already exists but -f/--overwrite was not set
shape: (121, 2)
┌─────────────────────────────────┬────────┐
│ phenotype                       ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u64    │
╞═════════════════════════════════╪════════╡
│ townsend_deprivation_index_at_… ┆ 462338 │
│ waist_circumference_int         ┆ 462018 │
│ hip_circumference_int           ┆ 461969 │
│ standing_height_int             ┆ 461803 │
│ weight_int                      ┆ 461477 │
│ …                               ┆ …      │
│ heel_bone_mineral_density_bmd_… ┆ 145953 │
│ heel_bone_mineral_density_bmd_… ┆ 145900 │
│ microalbumin_in_urine_int       ┆ 139887 │
│ age_at_hysterectomy_int         ┆ 47159  │
│ stroke_volume_during_pwa_int    ┆ 37110  │
└─────────────────────────────────┴────────┘

shape: (49_200_573, 3)
┌─────────┬─────────────────────────────┬─────────────┐
│ sample  ┆ phenotype                   ┆ pheno_value │
│ ---     ┆ ---                         ┆ ---         │
│ str     ┆ str                         ┆ f64         │
╞═════════╪═════════════════════════════╪═════════════╡
│ 1000020 ┆ reticulocyte_percentage_int ┆ -0.909716   │
│ 1000107 ┆ reticulocyte_percentage_int ┆ -0.205456   │
│ 1000161 ┆ reticulocyte_percentage_int ┆ 0.608602    │
│ 1000199 ┆ reticulocyte_percentage_int ┆ -1.344078   │
│ 1000206 ┆ reticulocyte_percentage_int ┆ 0.252129    │
│ …       ┆ …                           ┆ …           │
│ 1463944 ┆ sitting_height_int          ┆ 0.422057    │
│ 6002311 ┆ sitting_height_int          ┆ 0.332123    │
│ 2277715 ┆ sitting_height_int          ┆ -0.299873   │
│ 2332162 ┆ sitting_height_int          ┆ 0.564941    │
│ 4594543 ┆ sitting_height_int          ┆ 0.78259     │
└─────────┴─────────────────────────────┴─────────────┘

In [6]:
# Download genotype (long gt) file
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/gt_long.parquet -o /home/dnanexus/data_dir/

long_gt = (
    pl.scan_parquet('/home/dnanexus/data_dir/gt_long.parquet')
    .select(['id', 'sample', 'gt'])
)
long_gt.head().collect()

Error: path "/home/dnanexus/data_dir/gt_long.parquet" already exists but
-f/--overwrite was not set

shape: (5, 3)
┌────────────────────────────┬─────────┬─────┐
│ id                         ┆ sample  ┆ gt  │
│ ---                        ┆ ---     ┆ --- │
│ str                        ┆ str     ┆ i8  │
╞════════════════════════════╪═════════╪═════╡
│ chr10:20020006:C:T         ┆ 5317620 ┆ 1   │
│ chr10:20020007:TTTTCTTGC:T ┆ 5546988 ┆ 1   │
│ chr10:20020010:T:C         ┆ 2793793 ┆ 1   │
│ chr10:20020014:G:A         ┆ 1722739 ┆ 1   │
│ chr10:20020014:G:A         ┆ 1139673 ┆ 1   │
└────────────────────────────┴─────────┴─────┘

In [8]:
output_dir = '/home/dnanexus/data_dir/appv_phenos'
!mkdir -p {output_dir}

# Get the list of phenotype columns (names) for aggregation
pheno_cols = [c for c in phenos.collect_schema().names() if c != "sample"]

# sel_pheno = 'standing_height_int'
for sel_pheno in tqdm(pheno_cols):
    print(f"Processing phenotype: {sel_pheno}")
    
    (
        anno_pheno.filter(pl.col('phenotype')==sel_pheno)
        .lazy()
        .join(
            long_gt,
            on='id',
            how='inner'
        )

        .join(
            long_phenos.filter(pl.col('phenotype')==sel_pheno).lazy(),
            on=['sample', 'phenotype'],
            how='inner'
        )

        .group_by(['id', 'region', 'phenotype'])
        .agg(
            n_individuals = pl.len().cast(pl.Int32),
            mean_pheno_value = pl.col('pheno_value').mean().cast(pl.Float32),
            std_pheno_value = pl.col('pheno_value').std().cast(pl.Float32),
        )

        .sink_parquet(f'{output_dir}/loftee_mac20_quant_pheno_assocs_EURunrelated_appv{sel_pheno}.parquet')
        # .collect(engine='streaming')
    )

  0%|          | 0/121 [00:00<?, ?it/s]

Processing phenotype: white_blood_cell_leukocyte_count_int

  1%|          | 1/121 [00:20<40:40, 20.34s/it]

Processing phenotype: sitting_height_int

  2%|▏         | 2/121 [00:45<45:49, 23.10s/it]

Processing phenotype: ldl_direct_int

  2%|▏         | 3/121 [01:05<42:53, 21.81s/it]

Processing phenotype: fathers_age_at_death_int

  3%|▎         | 4/121 [01:25<41:06, 21.08s/it]

Processing phenotype: mean_corpuscular_haemoglobin_concentration_int

  4%|▍         | 5/121 [01:46<40:24, 20.90s/it]

Processing phenotype: forced_expiratory_volume_in_1second_fev1_int

  5%|▍         | 6/121 [02:09<41:45, 21.79s/it]

Processing phenotype: creactive_protein_int

  6%|▌         | 7/121 [02:30<40:33, 21.35s/it]

Processing phenotype: heel_bone_mineral_density_bmd_left_int

  7%|▋         | 8/121 [02:50<39:38, 21.05s/it]

Processing phenotype: mean_sphered_cell_volume_int

  7%|▋         | 9/121 [03:11<39:01, 20.91s/it]

Processing phenotype: apolipoprotein_b_int

  8%|▊         | 10/121 [03:31<38:22, 20.74s/it]

Processing phenotype: red_blood_cell_erythrocyte_distribution_width_int

  9%|▉         | 11/121 [03:52<38:13, 20.85s/it]

Processing phenotype: arm_fat_percentage_left_int

 10%|▉         | 12/121 [04:13<37:45, 20.78s/it]

Processing phenotype: mean_corpuscular_volume_int

 11%|█         | 13/121 [04:34<37:46, 20.98s/it]

Processing phenotype: body_mass_index_bmi_int

 12%|█▏        | 14/121 [04:56<37:43, 21.15s/it]

Processing phenotype: neutrophill_count_int

 12%|█▏        | 15/121 [05:17<37:15, 21.09s/it]

Processing phenotype: forced_vital_capacity_fvc_best_measure_int

 13%|█▎        | 16/121 [05:40<38:06, 21.78s/it]

Processing phenotype: whole_body_fat_mass_int

 14%|█▍        | 17/121 [06:01<37:15, 21.50s/it]

Processing phenotype: leg_predicted_mass_right_int

 15%|█▍        | 18/121 [06:24<37:37, 21.92s/it]

Processing phenotype: igf1_int

 16%|█▌        | 19/121 [06:45<36:52, 21.69s/it]

Processing phenotype: leg_predicted_mass_left_int

 17%|█▋        | 20/121 [07:07<36:48, 21.86s/it]

Processing phenotype: leg_fatfree_mass_left_int

 17%|█▋        | 21/121 [07:30<37:01, 22.21s/it]

Processing phenotype: calcium_int

 18%|█▊        | 22/121 [07:50<35:30, 21.52s/it]

Processing phenotype: high_light_scatter_reticulocyte_percentage_int

 19%|█▉        | 23/121 [08:11<34:46, 21.30s/it]

Processing phenotype: arm_fat_mass_left_int

 20%|█▉        | 24/121 [08:32<34:26, 21.30s/it]

Processing phenotype: heel_bone_mineral_density_bmd_tscore_automated_int

 21%|██        | 25/121 [08:52<33:29, 20.93s/it]

Processing phenotype: age_at_hysterectomy_int

 21%|██▏       | 26/121 [09:12<32:30, 20.53s/it]

Processing phenotype: basal_metabolic_rate_int

 22%|██▏       | 27/121 [09:35<33:24, 21.32s/it]

Processing phenotype: microalbumin_in_urine_int

 23%|██▎       | 28/121 [09:55<32:18, 20.84s/it]

Processing phenotype: hand_grip_strength_left_int

 24%|██▍       | 29/121 [10:16<32:10, 20.98s/it]

Processing phenotype: red_blood_cell_erythrocyte_count_int

 25%|██▍       | 30/121 [10:37<31:50, 20.99s/it]

Processing phenotype: pulse_rate_int

 26%|██▌       | 31/121 [10:57<30:55, 20.62s/it]

Processing phenotype: hdl_cholesterol_int

 26%|██▋       | 32/121 [11:18<30:38, 20.65s/it]

Processing phenotype: urate_int

 27%|██▋       | 33/121 [11:38<30:13, 20.61s/it]

Processing phenotype: birth_weight_int

 28%|██▊       | 34/121 [11:58<29:39, 20.46s/it]

Processing phenotype: aspartate_aminotransferase_int

 29%|██▉       | 35/121 [12:18<29:11, 20.37s/it]

Processing phenotype: basophill_percentage_int

 30%|██▉       | 36/121 [12:38<28:35, 20.19s/it]

Processing phenotype: age_started_wearing_glasses_or_contact_lenses_int

 31%|███       | 37/121 [12:58<28:15, 20.18s/it]

Processing phenotype: lymphocyte_count_int

 31%|███▏      | 38/121 [13:19<28:10, 20.37s/it]

Processing phenotype: mean_reticulocyte_volume_int

 32%|███▏      | 39/121 [13:40<28:02, 20.52s/it]

Processing phenotype: waist_circumference_int

 33%|███▎      | 40/121 [14:01<27:57, 20.71s/it]

Processing phenotype: arm_predicted_mass_right_int

 34%|███▍      | 41/121 [14:23<28:10, 21.13s/it]

Processing phenotype: basophill_count_int

 35%|███▍      | 42/121 [14:43<27:14, 20.69s/it]

Processing phenotype: body_fat_percentage_int

 36%|███▌      | 43/121 [15:03<26:47, 20.61s/it]

Processing phenotype: heel_bone_mineral_density_bmd_right_int

 36%|███▋      | 44/121 [15:23<26:13, 20.43s/it]

Processing phenotype: apolipoprotein_a_int

 37%|███▋      | 45/121 [15:44<25:50, 20.40s/it]

Processing phenotype: mean_corpuscular_haemoglobin_int

 38%|███▊      | 46/121 [16:05<25:58, 20.78s/it]

Processing phenotype: arm_fatfree_mass_right_int

 39%|███▉      | 47/121 [16:28<26:21, 21.37s/it]

Processing phenotype: fluid_intelligence_score_int

 40%|███▉      | 48/121 [16:48<25:24, 20.88s/it]

Processing phenotype: alanine_aminotransferase_int

 40%|████      | 49/121 [17:08<24:42, 20.59s/it]

Processing phenotype: triglycerides_int

 41%|████▏     | 50/121 [17:28<24:23, 20.62s/it]

Processing phenotype: hip_circumference_int

 42%|████▏     | 51/121 [17:49<24:04, 20.64s/it]

Processing phenotype: urea_int

 43%|████▎     | 52/121 [18:09<23:27, 20.40s/it]

Processing phenotype: glycated_haemoglobin_hba1c_int

 44%|████▍     | 53/121 [18:30<23:19, 20.58s/it]

Processing phenotype: heel_bone_mineral_density_bmd_tscore_automated_right_int

 45%|████▍     | 54/121 [18:50<22:44, 20.36s/it]

Processing phenotype: leg_fat_percentage_right_int

 45%|████▌     | 55/121 [19:12<23:06, 21.00s/it]

Processing phenotype: direct_bilirubin_int

 46%|████▋     | 56/121 [19:33<22:30, 20.78s/it]

Processing phenotype: eosinophill_percentage_int

 47%|████▋     | 57/121 [19:53<22:03, 20.68s/it]

Processing phenotype: peak_expiratory_flow_pef_int

 48%|████▊     | 58/121 [20:14<21:48, 20.78s/it]

Processing phenotype: trunk_fat_mass_int

 49%|████▉     | 59/121 [20:34<21:16, 20.58s/it]

Processing phenotype: reticulocyte_count_int

 50%|████▉     | 60/121 [20:55<21:03, 20.71s/it]

Processing phenotype: standing_height_int

 50%|█████     | 61/121 [21:22<22:26, 22.45s/it]

Processing phenotype: total_protein_int

 51%|█████     | 62/121 [21:42<21:25, 21.79s/it]

Processing phenotype: trunk_fatfree_mass_int

 52%|█████▏    | 63/121 [22:04<21:14, 21.98s/it]

Processing phenotype: hand_grip_strength_right_int

 53%|█████▎    | 64/121 [22:25<20:35, 21.67s/it]

Processing phenotype: townsend_deprivation_index_at_recruitment_int

 54%|█████▎    | 65/121 [22:46<19:54, 21.33s/it]

Processing phenotype: whole_body_fatfree_mass_int

 55%|█████▍    | 66/121 [23:09<20:05, 21.92s/it]

Processing phenotype: seated_height_int

 55%|█████▌    | 67/121 [23:32<19:54, 22.13s/it]

Processing phenotype: systolic_blood_pressure_automated_reading_int

 56%|█████▌    | 68/121 [23:52<18:58, 21.48s/it]

Processing phenotype: vitamin_d_int

 57%|█████▋    | 69/121 [24:12<18:21, 21.18s/it]

Processing phenotype: forced_expiratory_volume_in_1second_fev1_predicted_percentage_int

 58%|█████▊    | 70/121 [24:32<17:41, 20.82s/it]

Processing phenotype: neutrophill_percentage_int

 59%|█████▊    | 71/121 [24:52<17:11, 20.64s/it]

Processing phenotype: testosterone_int

 60%|█████▉    | 72/121 [25:12<16:41, 20.44s/it]

Processing phenotype: arm_fatfree_mass_left_int

 60%|██████    | 73/121 [25:35<16:46, 20.96s/it]

Processing phenotype: albumin_int

 61%|██████    | 74/121 [25:55<16:12, 20.70s/it]

Processing phenotype: leg_fatfree_mass_right_int

 62%|██████▏   | 75/121 [26:17<16:18, 21.27s/it]

Processing phenotype: shbg_int

 63%|██████▎   | 76/121 [26:38<15:44, 20.99s/it]

Processing phenotype: monocyte_percentage_int

 64%|██████▎   | 77/121 [26:58<15:15, 20.81s/it]

Processing phenotype: platelet_distribution_width_int

 64%|██████▍   | 78/121 [27:18<14:50, 20.71s/it]

Processing phenotype: cholesterol_int

 65%|██████▌   | 79/121 [27:39<14:28, 20.68s/it]

Processing phenotype: phosphate_int

 66%|██████▌   | 80/121 [27:59<13:56, 20.39s/it]

Processing phenotype: arm_fat_percentage_right_int

 67%|██████▋   | 81/121 [28:19<13:38, 20.47s/it]

Processing phenotype: weight_int

 68%|██████▊   | 82/121 [28:41<13:35, 20.92s/it]

Processing phenotype: weight_impedance_int

 69%|██████▊   | 83/121 [29:03<13:24, 21.17s/it]

Processing phenotype: stroke_volume_during_pwa_int

 69%|██████▉   | 84/121 [29:23<12:46, 20.70s/it]

Processing phenotype: forced_expiratory_volume_in_1second_fev1_best_measure_int

 70%|███████   | 85/121 [29:44<12:32, 20.92s/it]

Processing phenotype: haemoglobin_concentration_int

 71%|███████   | 86/121 [30:05<12:07, 20.79s/it]

Processing phenotype: trunk_predicted_mass_int

 72%|███████▏  | 87/121 [30:27<12:02, 21.25s/it]

Processing phenotype: glucose_int

 73%|███████▎  | 88/121 [30:47<11:30, 20.92s/it]

Processing phenotype: lipoprotein_a_int

 74%|███████▎  | 89/121 [31:07<11:02, 20.69s/it]

Processing phenotype: leg_fat_mass_right_int

 74%|███████▍  | 90/121 [31:28<10:38, 20.59s/it]

Processing phenotype: arm_predicted_mass_left_int

 75%|███████▌  | 91/121 [31:49<10:29, 20.98s/it]

Processing phenotype: heel_bone_mineral_density_bmd_tscore_automated_left_int

 76%|███████▌  | 92/121 [32:10<10:01, 20.74s/it]

Processing phenotype: immature_reticulocyte_fraction_int

 77%|███████▋  | 93/121 [32:30<09:35, 20.54s/it]

Processing phenotype: whole_body_water_mass_int

 78%|███████▊  | 94/121 [32:53<09:33, 21.25s/it]

Processing phenotype: mean_platelet_thrombocyte_volume_int

 79%|███████▊  | 95/121 [33:14<09:14, 21.33s/it]

Processing phenotype: forced_vital_capacity_fvc_int

 79%|███████▉  | 96/121 [33:39<09:16, 22.26s/it]

Processing phenotype: gamma_glutamyltransferase_int

 80%|████████  | 97/121 [34:00<08:44, 21.87s/it]

Processing phenotype: platelet_crit_int

 81%|████████  | 98/121 [34:20<08:15, 21.52s/it]

Processing phenotype: alkaline_phosphatase_int

 82%|████████▏ | 99/121 [34:41<07:45, 21.18s/it]

Processing phenotype: body_mass_index_bmi_impedance_int

 83%|████████▎ | 100/121 [35:02<07:25, 21.23s/it]

Processing phenotype: creatinine_int

 83%|████████▎ | 101/121 [35:23<07:04, 21.25s/it]

Processing phenotype: mothers_age_at_death_int

 84%|████████▍ | 102/121 [35:43<06:34, 20.78s/it]

Processing phenotype: creatinine_enzymatic_in_urine_int

 85%|████████▌ | 103/121 [36:03<06:07, 20.43s/it]

Processing phenotype: platelet_count_int

 86%|████████▌ | 104/121 [36:23<05:47, 20.42s/it]

Processing phenotype: monocyte_count_int

 87%|████████▋ | 105/121 [36:44<05:27, 20.48s/it]

Processing phenotype: diastolic_blood_pressure_automated_reading_int

 88%|████████▊ | 106/121 [37:04<05:07, 20.48s/it]

Processing phenotype: leg_fat_percentage_left_int

 88%|████████▊ | 107/121 [37:24<04:45, 20.41s/it]

Processing phenotype: position_of_pulse_wave_notch_int

 89%|████████▉ | 108/121 [37:44<04:24, 20.33s/it]

Processing phenotype: forced_expiratory_volume_in_1second_fev1_predicted_int

 90%|█████████ | 109/121 [38:05<04:04, 20.37s/it]

Processing phenotype: total_bilirubin_int

 91%|█████████ | 110/121 [38:25<03:43, 20.33s/it]

Processing phenotype: lymphocyte_percentage_int

 92%|█████████▏| 111/121 [38:46<03:24, 20.41s/it]

Processing phenotype: pulse_rate_automated_reading_int

 93%|█████████▎| 112/121 [39:06<03:04, 20.46s/it]

Processing phenotype: mean_time_to_correctly_identify_matches_int

 93%|█████████▎| 113/121 [39:26<02:42, 20.30s/it]

Processing phenotype: eosinophill_count_int

 94%|█████████▍| 114/121 [39:46<02:21, 20.20s/it]

Processing phenotype: haematocrit_percentage_int

 95%|█████████▌| 115/121 [40:07<02:02, 20.36s/it]

Processing phenotype: reticulocyte_percentage_int

 96%|█████████▌| 116/121 [40:28<01:42, 20.47s/it]

Processing phenotype: leg_fat_mass_left_int

 97%|█████████▋| 117/121 [40:48<01:21, 20.39s/it]

Processing phenotype: cystatin_c_int

 98%|█████████▊| 118/121 [41:10<01:02, 20.89s/it]

Processing phenotype: high_light_scatter_reticulocyte_count_int

 98%|█████████▊| 119/121 [41:31<00:41, 20.91s/it]

Processing phenotype: trunk_fat_percentage_int

 99%|█████████▉| 120/121 [41:51<00:20, 20.80s/it]

Processing phenotype: arm_fat_mass_right_int

100%|██████████| 121/121 [42:12<00:00, 20.93s/it]

## Consolidate parquet

In [10]:
combined_output_file = "/home/dnanexus/data_dir/loftee_mac20_quant_pheno_assocs_EURunrelated_appv.parquet"

# 1. Get list of files manually
files = glob.glob(output_dir)
print(f"Found {len(files)} files.")

# 2. Create a list of LazyFrames
lfs = [pl.scan_parquet(f) for f in files]

# 3. Concatenate with relaxation
combined_lazy = pl.concat(lfs, how="vertical_relaxed")

# 4. Stream to disk
print("Streaming to disk...")
combined_lazy.sink_parquet(combined_output_file, engine='streaming')
print("Done.")

Found 1 files.
Streaming to disk...
Done.

In [12]:
pl.scan_parquet(combined_output_file).head().collect()

shape: (5, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ id             ┆ region         ┆ phenotype      ┆ n_individuals ┆ mean_pheno_va ┆ std_pheno_val │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ lue           ┆ ue            │
│ str            ┆ str            ┆ str            ┆ i32           ┆ ---           ┆ ---           │
│                ┆                ┆                ┆               ┆ f32           ┆ f32           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ chr2:47802011: ┆ ENSG0000011606 ┆ age_at_hystere ┆ 1             ┆ 0.524274      ┆ null          │
│ A:G            ┆ 2              ┆ ctomy_int      ┆               ┆               ┆               │
│ chr2:47734223: ┆ ENSG0000011606 ┆ age_at_hystere ┆ 1             ┆ -0.286135     ┆ null          │
│ G:A            ┆ 2              ┆ ctomy_int      ┆               ┆               ┆               │
│ chr2:47772891: ┆ ENSG0000011606 ┆ age_at_hystere ┆ 1             ┆ 1.24687       ┆ null          │
│ C:T            ┆ 2              ┆ ctomy_int      ┆               ┆               ┆               │
│ chr2:47724289: ┆ ENSG0000011606 ┆ age_at_hystere ┆ 1             ┆ 1.888288      ┆ null          │
│ A:G            ┆ 2              ┆ ctomy_int      ┆               ┆               ┆               │
│ chr2:47784701: ┆ ENSG0000011606 ┆ age_at_hystere ┆ 1             ┆ -1.353767     ┆ null          │
│ G:C            ┆ 2              ┆ ctomy_int      ┆               ┆               ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘