In [1]:
import glob
import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm

In [2]:
# Download associaiton file
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results/regenie_127phenotypes_lofteeHC_mac20.parquet -o /home/dnanexus/data_dir/
# !dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/REGENIE_results/loftee_mac20_associations_bh_corrected.parquet -o /home/dnanexus/data_dir/

bt = pl.read_parquet('/home/dnanexus/data_dir/regenie_127phenotypes_lofteeHC_mac20.parquet')
bt = bt.filter(pl.col('pval_fdr')<=0.05)
bt

dxpy.utils.resolver.ResolutionError: Unable to resolve "regenie_127phenotypes_lofteeHC_mac20.parquet" to a data object or folder name in '/processed_data/REGENIE_results'

shape: (2_289, 21)
┌────────────┬─────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ region     ┆ chr ┆ phenotype  ┆ cohort     ┆ … ┆ controls_a ┆ info       ┆ pval_fdr  ┆ pval_bonf │
│ ---        ┆ --- ┆ ---        ┆ ---        ┆   ┆ lt         ┆ ---        ┆ ---       ┆ ---       │
│ str        ┆ i64 ┆ str        ┆ str        ┆   ┆ ---        ┆ str        ┆ f64       ┆ f64       │
│            ┆     ┆            ┆            ┆   ┆ str        ┆            ┆           ┆           │
╞════════════╪═════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ ENSG000001 ┆ 1   ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.000007  ┆ 0.003328  │
│ 32855      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.076632; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=128.00 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000000 ┆ 11  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.038502  ┆ 1.0       │
│ 52841      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.196317; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=38.000 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 11  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.003376  ┆ 1.0       │
│ 10243      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.094032; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=85.001 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 11  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 4.5099e-4 ┆ 1.3530e-4 │
│ 18137      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.173370; ┆ 6         ┆ 4         │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=25.000 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 12  ┆ apolipopro ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.006545  ┆ 1.0       │
│ 73064      ┆     ┆ tein_a_int ┆ n_lofteeHC ┆   ┆            ┆ =0.189177; ┆           ┆           │
│            ┆     ┆            ┆ _mac20     ┆   ┆            ┆ MAC=41.000 ┆           ┆           │
│            ┆     ┆            ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ …          ┆ …   ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ ENSG000001 ┆ 7   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.02095   ┆ 1.0       │
│ 82095      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.200004; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=24.500 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 8   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.036208  ┆ 1.0       │
│ 64741      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.155565; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=40.500 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000002 ┆ 8   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.045581  ┆ 1.0       │
│ 05189      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.156523; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=20.000 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000001 ┆ 9   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.027724  ┆ 1.0       │
│ 82752      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.161667; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=36.500 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
│ ENSG000000 ┆ 9   ┆ forced_exp ┆ scores_bge ┆ … ┆ NA         ┆ REGENIE_SE ┆ 0.045758  ┆ 1.0       │
│ 56586      ┆     ┆ iratory_vo ┆ n_lofteeHC ┆   ┆            ┆ =0.129988; ┆           ┆           │
│            ┆     ┆ lume_in_1s ┆ _mac20     ┆   ┆            ┆ MAC=29.000 ┆           ┆           │
│            ┆     ┆ …          ┆            ┆   ┆            ┆ …          ┆           ┆           │
└────────────┴─────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [3]:
# Download annotation file for variant-gene mapping
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/annotations_fill_na.parquet -o /home/dnanexus/data_dir/

anno = pl.read_parquet(
    '/home/dnanexus/data_dir/annotations_fill_na.parquet', 
    columns=['id', 'region']
)

anno

Error: path "/home/dnanexus/data_dir/annotations_fill_na.parquet" already
exists but -f/--overwrite was not set

shape: (74_534_850, 2)
┌─────────────────────┬─────────────────┐
│ id                  ┆ region          │
│ ---                 ┆ ---             │
│ str                 ┆ str             │
╞═════════════════════╪═════════════════╡
│ chr18:56603287:T:G  ┆ ENSG00000091164 │
│ chr18:56611517:A:G  ┆ ENSG00000091164 │
│ chr19:34340475:G:A  ┆ ENSG00000166398 │
│ chr19:5256210:T:C   ┆ ENSG00000105426 │
│ chr19:5257316:G:C   ┆ ENSG00000105426 │
│ …                   ┆ …               │
│ chr16:179290:T:A    ┆ ENSG00000086506 │
│ chr7:148348869:A:G  ┆ ENSG00000174469 │
│ chr5:138680487:A:G  ┆ ENSG00000044115 │
│ chr4:70839545:A:G   ┆ ENSG00000132463 │
│ chr15:72103067:A:AC ┆ ENSG00000066933 │
└─────────────────────┴─────────────────┘

In [4]:
anno_pheno = (
    anno.join(
        bt.select(['region', 'phenotype']).unique(), 
        on='region', 
        how='inner'
    )
)

anno_pheno

shape: (75_468_554, 3)
┌─────────────────────┬─────────────────┬─────────────────────────────────┐
│ id                  ┆ region          ┆ phenotype                       │
│ ---                 ┆ ---             ┆ ---                             │
│ str                 ┆ str             ┆ str                             │
╞═════════════════════╪═════════════════╪═════════════════════════════════╡
│ chr19:34340475:G:A  ┆ ENSG00000166398 ┆ sitting_height_int              │
│ chr19:34340475:G:A  ┆ ENSG00000166398 ┆ seated_height_int               │
│ chr2:215390704:C:T  ┆ ENSG00000115414 ┆ forced_expiratory_volume_in_1s… │
│ chr2:178702309:A:G  ┆ ENSG00000155657 ┆ hand_grip_strength_left_int     │
│ chr2:178702309:A:G  ┆ ENSG00000155657 ┆ leg_fatfree_mass_left_int       │
│ …                   ┆ …               ┆ …                               │
│ chr15:72103059:G:GC ┆ ENSG00000066933 ┆ sitting_height_int              │
│ chr17:64662044:G:C  ┆ ENSG00000108854 ┆ standing_height_int             │
│ chr17:64662044:G:C  ┆ ENSG00000108854 ┆ forced_vital_capacity_fvc_int   │
│ chr2:158525435:T:C  ┆ ENSG00000144283 ┆ hip_circumference_int           │
│ chr15:72103067:A:AC ┆ ENSG00000066933 ┆ sitting_height_int              │
└─────────────────────┴─────────────────┴─────────────────────────────────┘

In [5]:
# Download phenotypes: covariates and PRS corrected
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/phenotypes/corrected_cov_PRS_traits_EUR.parquet -o /home/dnanexus/data_dir/

phenos = (
    pl.read_parquet('/home/dnanexus/data_dir/corrected_cov_PRS_traits_EUR.parquet')
    .select(['individual'] + bt['phenotype'].unique().to_list())
    .rename({'individual':'sample'})
)

# phenos

long_phenos = (
    phenos
    .unpivot(
        index='sample',
        on=bt['phenotype'].unique().to_list(),
        variable_name='phenotype',
        value_name='pheno_value'
    )
    .drop_nulls()
)

print(long_phenos['phenotype'].value_counts(sort=True))
long_phenos

Error: path "/home/dnanexus/data_dir/corrected_cov_PRS_traits_EUR.parquet"
already exists but -f/--overwrite was not set
shape: (121, 2)
┌─────────────────────────────────┬────────┐
│ phenotype                       ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u64    │
╞═════════════════════════════════╪════════╡
│ townsend_deprivation_index_at_… ┆ 462338 │
│ waist_circumference_int         ┆ 462018 │
│ hip_circumference_int           ┆ 461969 │
│ standing_height_int             ┆ 461803 │
│ weight_int                      ┆ 461477 │
│ …                               ┆ …      │
│ heel_bone_mineral_density_bmd_… ┆ 145953 │
│ heel_bone_mineral_density_bmd_… ┆ 145900 │
│ microalbumin_in_urine_int       ┆ 139887 │
│ age_at_hysterectomy_int         ┆ 47159  │
│ stroke_volume_during_pwa_int    ┆ 37110  │
└─────────────────────────────────┴────────┘

shape: (49_200_573, 3)
┌─────────┬─────────────────────────────┬─────────────┐
│ sample  ┆ phenotype                   ┆ pheno_value │
│ ---     ┆ ---                         ┆ ---         │
│ str     ┆ str                         ┆ f64         │
╞═════════╪═════════════════════════════╪═════════════╡
│ 1000020 ┆ leg_fat_percentage_left_int ┆ -0.510343   │
│ 1000107 ┆ leg_fat_percentage_left_int ┆ -0.54249    │
│ 1000161 ┆ leg_fat_percentage_left_int ┆ -0.332118   │
│ 1000172 ┆ leg_fat_percentage_left_int ┆ 0.340917    │
│ 1000199 ┆ leg_fat_percentage_left_int ┆ 0.172168    │
│ …       ┆ …                           ┆ …           │
│ 2750445 ┆ whole_body_water_mass_int   ┆ -0.148488   │
│ 1463944 ┆ whole_body_water_mass_int   ┆ -0.109719   │
│ 6002311 ┆ whole_body_water_mass_int   ┆ -0.219951   │
│ 2277715 ┆ whole_body_water_mass_int   ┆ -0.68317    │
│ 2332162 ┆ whole_body_water_mass_int   ┆ 0.555392    │
└─────────┴─────────────────────────────┴─────────────┘

In [6]:
# Download genotype (long gt) file
!dx download project-Gyp4fvjJg0yFZ374KvP9bGFJ:/processed_data/wgs/qced_maf1e-3_loftee_olink_genes/qced_maf1e-3_loftee_olink_genes_EURunrelated/gt_long.parquet -o /home/dnanexus/data_dir/

long_gt = (
    pl.scan_parquet('/home/dnanexus/data_dir/gt_long.parquet')
    .select(['id', 'sample', 'gt'])
    .filter(pl.col('gt')==1)
)
long_gt.head().collect()

Error: path "/home/dnanexus/data_dir/gt_long.parquet" already exists but
-f/--overwrite was not set

shape: (5, 3)
┌────────────────────────────┬─────────┬─────┐
│ id                         ┆ sample  ┆ gt  │
│ ---                        ┆ ---     ┆ --- │
│ str                        ┆ str     ┆ i8  │
╞════════════════════════════╪═════════╪═════╡
│ chr10:20020006:C:T         ┆ 5317620 ┆ 1   │
│ chr10:20020007:TTTTCTTGC:T ┆ 5546988 ┆ 1   │
│ chr10:20020010:T:C         ┆ 2793793 ┆ 1   │
│ chr10:20020014:G:A         ┆ 1722739 ┆ 1   │
│ chr10:20020014:G:A         ┆ 1139673 ┆ 1   │
└────────────────────────────┴─────────┴─────┘

In [7]:
output_dir = '/home/dnanexus/data_dir/appv_phenos'
!mkdir -p {output_dir}

# Get the list of phenotype columns (names) for aggregation
pheno_cols = [c for c in phenos.collect_schema().names() if c != "sample"]

# sel_pheno = 'standing_height_int'
for sel_pheno in tqdm(pheno_cols):
    print(f"Processing phenotype: {sel_pheno}")
    
    (
        anno_pheno.filter(pl.col('phenotype')==sel_pheno)
        .lazy()
        .join(
            long_gt,
            on='id',
            how='inner'
        )

        .join(
            long_phenos.filter(pl.col('phenotype')==sel_pheno).lazy(),
            on=['sample', 'phenotype'],
            how='inner'
        )

        .group_by(['id', 'region', 'phenotype'])
        .agg(
            n_individuals = pl.len().cast(pl.Int32),
            mean_pheno_value = pl.col('pheno_value').mean().cast(pl.Float32),
            std_pheno_value = pl.col('pheno_value').std().cast(pl.Float32),
        )

        .with_columns(
            mean_pheno_value_rank=pl.col('mean_pheno_value')
                .rank(method="max")
                .over("region")
                .cast(pl.Float32)
        )
        .with_columns(
            mean_pheno_value_ptile=(
                pl.col('mean_pheno_value_rank') / pl.len()
            ).cast(pl.Float32)
        )

        .sink_parquet(f'{output_dir}/loftee_mac20_quant_pheno_assocs_EURunrelated_appv{sel_pheno}.parquet')
        # .collect(engine='streaming')
    )

  0%|          | 0/121 [00:00<?, ?it/s]

Processing phenotype: arm_fat_percentage_right_int

  1%|          | 1/121 [00:12<25:41, 12.84s/it]

Processing phenotype: mean_time_to_correctly_identify_matches_int

  2%|▏         | 2/121 [00:25<25:02, 12.63s/it]

Processing phenotype: systolic_blood_pressure_automated_reading_int

  2%|▏         | 3/121 [00:37<24:22, 12.39s/it]

Processing phenotype: monocyte_count_int

  3%|▎         | 4/121 [00:49<23:59, 12.30s/it]

Processing phenotype: age_started_wearing_glasses_or_contact_lenses_int

  4%|▍         | 5/121 [01:01<23:33, 12.18s/it]

Processing phenotype: red_blood_cell_erythrocyte_count_int

  5%|▍         | 6/121 [01:13<23:26, 12.23s/it]

Processing phenotype: mean_sphered_cell_volume_int

  6%|▌         | 7/121 [01:26<23:18, 12.27s/it]

Processing phenotype: trunk_fatfree_mass_int

  7%|▋         | 8/121 [01:39<23:47, 12.63s/it]

Processing phenotype: vitamin_d_int

  7%|▋         | 9/121 [01:51<23:16, 12.47s/it]

Processing phenotype: direct_bilirubin_int

  8%|▊         | 10/121 [02:03<22:54, 12.38s/it]

Processing phenotype: forced_expiratory_volume_in_1second_fev1_best_measure_int

  9%|▉         | 11/121 [02:16<22:45, 12.42s/it]

Processing phenotype: total_bilirubin_int

 10%|▉         | 12/121 [02:28<22:28, 12.37s/it]

Processing phenotype: triglycerides_int

 11%|█         | 13/121 [02:41<22:21, 12.42s/it]

Processing phenotype: mean_corpuscular_volume_int

 12%|█▏        | 14/121 [02:53<22:11, 12.45s/it]

Processing phenotype: urea_int

 12%|█▏        | 15/121 [03:05<21:46, 12.32s/it]

Processing phenotype: heel_bone_mineral_density_bmd_tscore_automated_int

 13%|█▎        | 16/121 [03:17<21:23, 12.22s/it]

Processing phenotype: reticulocyte_count_int

 14%|█▍        | 17/121 [03:30<21:14, 12.26s/it]

Processing phenotype: forced_vital_capacity_fvc_best_measure_int

 15%|█▍        | 18/121 [03:43<21:36, 12.58s/it]

Processing phenotype: body_mass_index_bmi_impedance_int

 16%|█▌        | 19/121 [03:56<21:27, 12.63s/it]

Processing phenotype: mean_corpuscular_haemoglobin_concentration_int

 17%|█▋        | 20/121 [04:08<21:01, 12.49s/it]

Processing phenotype: heel_bone_mineral_density_bmd_left_int

 17%|█▋        | 21/121 [04:20<20:30, 12.31s/it]

Processing phenotype: waist_circumference_int

 18%|█▊        | 22/121 [04:32<20:23, 12.36s/it]

Processing phenotype: lymphocyte_percentage_int

 19%|█▉        | 23/121 [04:44<20:07, 12.32s/it]

Processing phenotype: stroke_volume_during_pwa_int

 20%|█▉        | 24/121 [04:57<19:55, 12.33s/it]

Processing phenotype: leg_fat_mass_right_int

 21%|██        | 25/121 [05:09<19:43, 12.32s/it]

Processing phenotype: basophill_percentage_int

 21%|██▏       | 26/121 [05:21<19:19, 12.21s/it]

Processing phenotype: high_light_scatter_reticulocyte_percentage_int

 22%|██▏       | 27/121 [05:33<19:11, 12.25s/it]

Processing phenotype: ldl_direct_int

 23%|██▎       | 28/121 [05:45<18:55, 12.20s/it]

Processing phenotype: hip_circumference_int

 24%|██▍       | 29/121 [05:58<18:51, 12.30s/it]

Processing phenotype: whole_body_water_mass_int

 25%|██▍       | 30/121 [06:11<19:00, 12.54s/it]

Processing phenotype: hand_grip_strength_right_int

 26%|██▌       | 31/121 [06:24<18:50, 12.56s/it]

Processing phenotype: arm_fatfree_mass_right_int

 26%|██▋       | 32/121 [06:37<18:46, 12.66s/it]

Processing phenotype: leg_fat_percentage_right_int

 27%|██▋       | 33/121 [06:49<18:29, 12.61s/it]

Processing phenotype: trunk_predicted_mass_int

 28%|██▊       | 34/121 [07:02<18:25, 12.71s/it]

Processing phenotype: platelet_crit_int

 29%|██▉       | 35/121 [07:15<18:12, 12.70s/it]

Processing phenotype: haematocrit_percentage_int

 30%|██▉       | 36/121 [07:27<17:48, 12.57s/it]

Processing phenotype: whole_body_fatfree_mass_int

 31%|███       | 37/121 [07:40<17:45, 12.69s/it]

Processing phenotype: neutrophill_percentage_int

 31%|███▏      | 38/121 [07:52<17:23, 12.57s/it]

Processing phenotype: heel_bone_mineral_density_bmd_tscore_automated_right_int

 32%|███▏      | 39/121 [08:04<16:55, 12.38s/it]

Processing phenotype: leg_fatfree_mass_left_int

 33%|███▎      | 40/121 [08:17<17:05, 12.66s/it]

Processing phenotype: cystatin_c_int

 34%|███▍      | 41/121 [08:30<16:56, 12.71s/it]

Processing phenotype: white_blood_cell_leukocyte_count_int

 35%|███▍      | 42/121 [08:43<16:31, 12.55s/it]

Processing phenotype: igf1_int

 36%|███▌      | 43/121 [08:55<16:15, 12.51s/it]

Processing phenotype: arm_fat_mass_right_int

 36%|███▋      | 44/121 [09:07<15:58, 12.45s/it]

Processing phenotype: age_at_hysterectomy_int

 37%|███▋      | 45/121 [09:19<15:39, 12.36s/it]

Processing phenotype: high_light_scatter_reticulocyte_count_int

 38%|███▊      | 46/121 [09:32<15:30, 12.41s/it]

Processing phenotype: leg_fat_mass_left_int

 39%|███▉      | 47/121 [09:44<15:15, 12.37s/it]

Processing phenotype: calcium_int

 40%|███▉      | 48/121 [09:56<14:55, 12.26s/it]

Processing phenotype: pulse_rate_int

 40%|████      | 49/121 [10:08<14:35, 12.16s/it]

Processing phenotype: immature_reticulocyte_fraction_int

 41%|████▏     | 50/121 [10:20<14:20, 12.12s/it]

Processing phenotype: aspartate_aminotransferase_int

 42%|████▏     | 51/121 [10:33<14:17, 12.25s/it]

Processing phenotype: phosphate_int

 43%|████▎     | 52/121 [10:45<13:58, 12.15s/it]

Processing phenotype: forced_expiratory_volume_in_1second_fev1_predicted_percentage_int

 44%|████▍     | 53/121 [10:57<13:44, 12.13s/it]

Processing phenotype: mean_corpuscular_haemoglobin_int

 45%|████▍     | 54/121 [11:09<13:43, 12.28s/it]

Processing phenotype: birth_weight_int

 45%|████▌     | 55/121 [11:21<13:23, 12.17s/it]

Processing phenotype: arm_predicted_mass_right_int

 46%|████▋     | 56/121 [11:34<13:29, 12.45s/it]

Processing phenotype: glycated_haemoglobin_hba1c_int

 47%|████▋     | 57/121 [11:47<13:16, 12.44s/it]

Processing phenotype: total_protein_int

 48%|████▊     | 58/121 [11:59<12:58, 12.35s/it]

Processing phenotype: seated_height_int

 49%|████▉     | 59/121 [12:12<12:57, 12.55s/it]

Processing phenotype: reticulocyte_percentage_int

 50%|████▉     | 60/121 [12:24<12:43, 12.52s/it]

Processing phenotype: platelet_count_int

 50%|█████     | 61/121 [12:37<12:28, 12.48s/it]

Processing phenotype: sitting_height_int

 51%|█████     | 62/121 [12:51<12:45, 12.98s/it]

Processing phenotype: arm_fatfree_mass_left_int

 52%|█████▏    | 63/121 [13:04<12:27, 12.89s/it]

Processing phenotype: heel_bone_mineral_density_bmd_tscore_automated_left_int

 53%|█████▎    | 64/121 [13:15<11:57, 12.59s/it]

Processing phenotype: arm_predicted_mass_left_int

 54%|█████▎    | 65/121 [13:28<11:45, 12.60s/it]

Processing phenotype: forced_expiratory_volume_in_1second_fev1_int

 55%|█████▍    | 66/121 [13:41<11:40, 12.73s/it]

Processing phenotype: townsend_deprivation_index_at_recruitment_int

 55%|█████▌    | 67/121 [13:54<11:26, 12.71s/it]

Processing phenotype: creatinine_int

 56%|█████▌    | 68/121 [14:06<11:07, 12.59s/it]

Processing phenotype: creatinine_enzymatic_in_urine_int

 57%|█████▋    | 69/121 [14:18<10:44, 12.39s/it]

Processing phenotype: alkaline_phosphatase_int

 58%|█████▊    | 70/121 [14:30<10:29, 12.35s/it]

Processing phenotype: platelet_distribution_width_int

 59%|█████▊    | 71/121 [14:43<10:16, 12.32s/it]

Processing phenotype: lipoprotein_a_int

 60%|█████▉    | 72/121 [14:55<10:02, 12.29s/it]

Processing phenotype: hand_grip_strength_left_int

 60%|██████    | 73/121 [15:07<09:55, 12.41s/it]

Processing phenotype: hdl_cholesterol_int

 61%|██████    | 74/121 [15:20<09:43, 12.40s/it]

Processing phenotype: fathers_age_at_death_int

 62%|██████▏   | 75/121 [15:32<09:25, 12.29s/it]

Processing phenotype: glucose_int

 63%|██████▎   | 76/121 [15:44<09:09, 12.22s/it]

Processing phenotype: monocyte_percentage_int

 64%|██████▎   | 77/121 [15:56<08:57, 12.21s/it]

Processing phenotype: testosterone_int

 64%|██████▍   | 78/121 [16:09<08:48, 12.29s/it]

Processing phenotype: trunk_fat_percentage_int

 65%|██████▌   | 79/121 [16:21<08:36, 12.31s/it]

Processing phenotype: position_of_pulse_wave_notch_int

 66%|██████▌   | 80/121 [16:33<08:19, 12.19s/it]

Processing phenotype: cholesterol_int

 67%|██████▋   | 81/121 [16:45<08:07, 12.18s/it]

Processing phenotype: arm_fat_percentage_left_int

 68%|██████▊   | 82/121 [16:57<07:56, 12.21s/it]

Processing phenotype: leg_fatfree_mass_right_int

 69%|██████▊   | 83/121 [17:10<07:54, 12.49s/it]

Processing phenotype: basal_metabolic_rate_int

 69%|██████▉   | 84/121 [17:23<07:48, 12.65s/it]

Processing phenotype: whole_body_fat_mass_int

 70%|███████   | 85/121 [17:36<07:33, 12.59s/it]

Processing phenotype: leg_predicted_mass_left_int

 71%|███████   | 86/121 [17:49<07:23, 12.68s/it]

Processing phenotype: creactive_protein_int

 72%|███████▏  | 87/121 [18:01<07:05, 12.52s/it]

Processing phenotype: neutrophill_count_int

 73%|███████▎  | 88/121 [18:13<06:50, 12.44s/it]

Processing phenotype: microalbumin_in_urine_int

 74%|███████▎  | 89/121 [18:25<06:36, 12.40s/it]

Processing phenotype: heel_bone_mineral_density_bmd_right_int

 74%|███████▍  | 90/121 [18:37<06:20, 12.27s/it]

Processing phenotype: albumin_int

 75%|███████▌  | 91/121 [18:50<06:06, 12.22s/it]

Processing phenotype: trunk_fat_mass_int

 76%|███████▌  | 92/121 [19:02<05:54, 12.21s/it]

Processing phenotype: gamma_glutamyltransferase_int

 77%|███████▋  | 93/121 [19:14<05:43, 12.27s/it]

Processing phenotype: weight_impedance_int

 78%|███████▊  | 94/121 [19:27<05:36, 12.48s/it]

Processing phenotype: lymphocyte_count_int

 79%|███████▊  | 95/121 [19:40<05:24, 12.48s/it]

Processing phenotype: red_blood_cell_erythrocyte_distribution_width_int

 79%|███████▉  | 96/121 [19:52<05:11, 12.47s/it]

Processing phenotype: shbg_int

 80%|████████  | 97/121 [20:04<04:56, 12.36s/it]

Processing phenotype: forced_vital_capacity_fvc_int

 81%|████████  | 98/121 [20:18<04:51, 12.68s/it]

Processing phenotype: weight_int

 82%|████████▏ | 99/121 [20:30<04:39, 12.71s/it]

Processing phenotype: standing_height_int

 83%|████████▎ | 100/121 [20:45<04:40, 13.33s/it]

Processing phenotype: basophill_count_int

 83%|████████▎ | 101/121 [20:57<04:18, 12.91s/it]

Processing phenotype: haemoglobin_concentration_int

 84%|████████▍ | 102/121 [21:09<04:01, 12.71s/it]

Processing phenotype: fluid_intelligence_score_int

 85%|████████▌ | 103/121 [21:21<03:44, 12.47s/it]

Processing phenotype: eosinophill_percentage_int

 86%|████████▌ | 104/121 [21:33<03:30, 12.39s/it]

Processing phenotype: pulse_rate_automated_reading_int

 87%|████████▋ | 105/121 [21:46<03:19, 12.48s/it]

Processing phenotype: peak_expiratory_flow_pef_int

 88%|████████▊ | 106/121 [21:59<03:07, 12.48s/it]

Processing phenotype: eosinophill_count_int

 88%|████████▊ | 107/121 [22:11<02:53, 12.38s/it]

Processing phenotype: forced_expiratory_volume_in_1second_fev1_predicted_int

 89%|████████▉ | 108/121 [22:23<02:40, 12.35s/it]

Processing phenotype: diastolic_blood_pressure_automated_reading_int

 90%|█████████ | 109/121 [22:35<02:28, 12.34s/it]

Processing phenotype: body_mass_index_bmi_int

 91%|█████████ | 110/121 [22:48<02:17, 12.52s/it]

Processing phenotype: mothers_age_at_death_int

 92%|█████████▏| 111/121 [23:00<02:03, 12.34s/it]

Processing phenotype: body_fat_percentage_int

 93%|█████████▎| 112/121 [23:13<01:51, 12.34s/it]

Processing phenotype: alanine_aminotransferase_int

 93%|█████████▎| 113/121 [23:25<01:37, 12.24s/it]

Processing phenotype: urate_int

 94%|█████████▍| 114/121 [23:37<01:25, 12.22s/it]

Processing phenotype: mean_platelet_thrombocyte_volume_int

 95%|█████████▌| 115/121 [23:49<01:14, 12.35s/it]

Processing phenotype: mean_reticulocyte_volume_int

 96%|█████████▌| 116/121 [24:02<01:02, 12.46s/it]

Processing phenotype: leg_predicted_mass_right_int

 97%|█████████▋| 117/121 [24:15<00:50, 12.58s/it]

Processing phenotype: apolipoprotein_a_int

 98%|█████████▊| 118/121 [24:27<00:37, 12.49s/it]

Processing phenotype: apolipoprotein_b_int

 98%|█████████▊| 119/121 [24:39<00:24, 12.37s/it]

Processing phenotype: leg_fat_percentage_left_int

 99%|█████████▉| 120/121 [24:52<00:12, 12.35s/it]

Processing phenotype: arm_fat_mass_left_int

100%|██████████| 121/121 [25:04<00:00, 12.44s/it]

## Consolidate parquet

In [8]:
combined_output_file = "/home/dnanexus/data_dir/loftee_mac20_quant_pheno_assocs_EURunrelated_appv_percentiles.parquet"

# 1. Get list of files manually
files = glob.glob(output_dir)
print(f"Found {len(files)} files.")

# 2. Create a list of LazyFrames
lfs = [pl.scan_parquet(f) for f in files]

# 3. Concatenate with relaxation
combined_lazy = pl.concat(lfs, how="vertical_relaxed")

# 4. Stream to disk
print("Streaming to disk...")
combined_lazy.sink_parquet(combined_output_file, engine='streaming')
print("Done.")

Found 1 files.
Streaming to disk...

Done.

In [9]:
pl.scan_parquet(combined_output_file).head().collect()

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ region     ┆ phenotype  ┆ n_individ ┆ mean_phen ┆ std_pheno ┆ mean_phen ┆ mean_phen │
│ ---        ┆ ---        ┆ ---        ┆ uals      ┆ o_value   ┆ _value    ┆ o_value_r ┆ o_value_p │
│ str        ┆ str        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ank       ┆ tile      │
│            ┆            ┆            ┆ i32       ┆ f32       ┆ f32       ┆ ---       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆           ┆ f32       ┆ f32       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ chr2:47749 ┆ ENSG000001 ┆ age_at_hys ┆ 1         ┆ 1.828922  ┆ null      ┆ 12605.0   ┆ 0.98886   │
│ 560:C:G    ┆ 16062      ┆ terectomy_ ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ int        ┆           ┆           ┆           ┆           ┆           │
│ chr2:47755 ┆ ENSG000001 ┆ age_at_hys ┆ 1         ┆ -0.102434 ┆ null      ┆ 5451.0    ┆ 0.42763   │
│ 663:C:T    ┆ 16062      ┆ terectomy_ ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ int        ┆           ┆           ┆           ┆           ┆           │
│ chr2:47752 ┆ ENSG000001 ┆ age_at_hys ┆ 1         ┆ 0.446505  ┆ null      ┆ 9353.0    ┆ 0.733741  │
│ 321:C:G    ┆ 16062      ┆ terectomy_ ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ int        ┆           ┆           ┆           ┆           ┆           │
│ chr2:47705 ┆ ENSG000001 ┆ age_at_hys ┆ 2         ┆ -0.979544 ┆ 1.11237   ┆ 1284.0    ┆ 0.10073   │
│ 366:C:T    ┆ 16062      ┆ terectomy_ ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ int        ┆           ┆           ┆           ┆           ┆           │
│ chr2:47701 ┆ ENSG000001 ┆ age_at_hys ┆ 1         ┆ 0.545061  ┆ null      ┆ 9847.0    ┆ 0.772496  │
│ 021:T:TAA  ┆ 16062      ┆ terectomy_ ┆           ┆           ┆           ┆           ┆           │
│            ┆            ┆ int        ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘