In [39]:
import zarr
import numpy as np
import polars as pl

In [3]:
anno = pl.read_parquet(f"/home/dnanexus/data_dir/genebass1e6_genes_10kb_allvars_annotated_250925.parquet", columns=['id', 'chrom', 'pos', 'ref', 'alt', 'region', 'gene_name'])
anno

shape: (90_570_107, 7)
┌─────────────────────┬───────┬───────────┬────────────────────┬─────┬─────────────────┬───────────┐
│ id                  ┆ chrom ┆ pos       ┆ ref                ┆ alt ┆ region          ┆ gene_name │
│ ---                 ┆ ---   ┆ ---       ┆ ---                ┆ --- ┆ ---             ┆ ---       │
│ str                 ┆ str   ┆ i32       ┆ str                ┆ str ┆ str             ┆ str       │
╞═════════════════════╪═══════╪═══════════╪════════════════════╪═════╪═════════════════╪═══════════╡
│ chr2:134144266:C:T  ┆ chr2  ┆ 134144266 ┆ C                  ┆ T   ┆ ENSG00000152127 ┆ MGAT5     │
│ chr2:134192587:C:T  ┆ chr2  ┆ 134192587 ┆ C                  ┆ T   ┆ ENSG00000152127 ┆ MGAT5     │
│ chr2:134389573:T:C  ┆ chr2  ┆ 134389573 ┆ T                  ┆ C   ┆ ENSG00000152127 ┆ MGAT5     │
│ chr2:127525503:G:A  ┆ chr2  ┆ 127525503 ┆ G                  ┆ A   ┆ ENSG00000163166 ┆ IWS1      │
│ chr2:134155422:C:T  ┆ chr2  ┆ 134155422 ┆ C                  ┆ T   ┆ ENSG00000152127 ┆ MGAT5     │
│ …                   ┆ …     ┆ …         ┆ …                  ┆ …   ┆ …               ┆ …         │
│ chr8:13200986:C:CA  ┆ chr8  ┆ 13200986  ┆ C                  ┆ CA  ┆ ENSG00000164741 ┆ DLC1      │
│ chr12:122075449:C:T ┆ chr12 ┆ 122075449 ┆ C                  ┆ T   ┆ ENSG00000175727 ┆ MLXIP     │
│ chr12:122065447:G:A ┆ chr12 ┆ 122065447 ┆ G                  ┆ A   ┆ ENSG00000110987 ┆ BCL7A     │
│ chr5:180321761:GGTT ┆ chr5  ┆ 180321761 ┆ GGTTTTGTTTTGTTTTGT ┆ G   ┆ ENSG00000131459 ┆ GFPT2     │
│ TTGTTTTGTTT…        ┆       ┆           ┆ TTTGTTTT           ┆     ┆                 ┆           │
│ chr3:51873798:CAAGT ┆ chr3  ┆ 51873798  ┆ CAAGTTGAATATT      ┆ C   ┆ ENSG00000214681 ┆ IQCF5     │
│ TGAATATT:C          ┆       ┆           ┆                    ┆     ┆                 ┆           │
└─────────────────────┴───────┴───────────┴────────────────────┴─────┴─────────────────┴───────────┘

In [18]:
olnk = pl.read_parquet("/home/dnanexus/data_dir/olink/olink_corrected_rint_90_pcs.parquet")
olnk

shape: (40_398, 372)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬─────────┐
│ ENSG000001 ┆ ENSG00000 ┆ ENSG00000 ┆ ENSG00000 ┆ … ┆ ENSG00000 ┆ ENSG00000 ┆ ENSG00000 ┆ sample  │
│ 20053      ┆ 140443    ┆ 084674    ┆ 015475    ┆   ┆ 167186    ┆ 025708    ┆ 066468    ┆ ---     │
│ ---        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str     │
│ f64        ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆         │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═════════╡
│ -0.592022  ┆ 2.477856  ┆ 0.354833  ┆ 0.036147  ┆ … ┆ -0.543771 ┆ 0.47082   ┆ 0.605257  ┆ 1000107 │
│ 0.061036   ┆ -0.530447 ┆ null      ┆ -1.253191 ┆ … ┆ 0.134858  ┆ 0.403499  ┆ -0.595941 ┆ 1001193 │
│ 0.228713   ┆ 1.297618  ┆ -0.425314 ┆ -0.576221 ┆ … ┆ 0.68994   ┆ -0.900913 ┆ 1.088444  ┆ 1001694 │
│ 0.674837   ┆ null      ┆ -1.180707 ┆ -1.542909 ┆ … ┆ 0.511896  ┆ -0.020851 ┆ 0.012056  ┆ 1001715 │
│ 1.153924   ┆ 0.184579  ┆ 0.169054  ┆ -0.94747  ┆ … ┆ 2.311388  ┆ 0.031901  ┆ 1.788948  ┆ 1002486 │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …       │
│ -0.491464  ┆ -1.242181 ┆ -0.485032 ┆ -0.047356 ┆ … ┆ -0.120259 ┆ null      ┆ 0.72708   ┆ 6019565 │
│ 0.308539   ┆ -0.150795 ┆ 0.662787  ┆ -0.508696 ┆ … ┆ -0.267713 ┆ null      ┆ -0.327369 ┆ 6019855 │
│ null       ┆ -1.1371   ┆ null      ┆ 0.87775   ┆ … ┆ null      ┆ 0.845785  ┆ 0.991073  ┆ 6021528 │
│ null       ┆ 1.816509  ┆ null      ┆ 0.451261  ┆ … ┆ null      ┆ 0.458587  ┆ -1.81022  ┆ 6022842 │
│ -1.338952  ┆ 1.345314  ┆ 0.652919  ┆ 0.343063  ┆ … ┆ null      ┆ -0.805801 ┆ 1.16358   ┆ 6023199 │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴─────────┘

In [21]:
anngeno_path = '/home/dnanexus/data_dir/genebass_1e6_coding_variants.ag'
eur_samples_path = '/home/dnanexus/data_dir/unrelated_cauc_samples_3rd_degree.csv'
# olink_path = '/home/dnanexus/data_dir/olink/protrider_lite_output/log2fc.csv'
olink_path = "/home/dnanexus/data_dir/olink/olink_corrected_rint_90_pcs.parquet"

In [11]:
sample_ids = zarr.open(f'{anngeno_path}/zarr_store/samples', mode='r')[:]
var_ids = pl.read_parquet(f'{anngeno_path}/variant_metadata.parquet', columns=['id'])['id'].to_numpy()
geno = zarr.open(f'{anngeno_path}/zarr_store/genotypes', mode='r')

/home/dnanexus/deeprvat2-env/lib/python3.11/site-packages/zarr/codecs/vlen_utf8.py:44: UserWarning: The codec `vlen-utf8` is currently not part in the Zarr format 3 specification. It may not be supported by other zarr implementations and may change in the future.
  return cls(**configuration_parsed)

In [23]:
eur_samples = pl.read_csv(eur_samples_path).rename({'eid': 'individual'}).with_columns(
    pl.col("individual").cast(pl.Utf8)
)['individual'].to_list()

olink_lazy = pl.read_parquet(olink_path).rename({'sample': 'individual'}).with_columns(
    pl.col("individual").cast(pl.Utf8)
).filter(
    pl.col("individual").is_in(eur_samples)
).fill_nan(None)

unique_phenotypes = [pheno for pheno in olink_lazy.columns if pheno != 'individual']

olink_lazy

shape: (40_398, 372)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ENSG00000 ┆ ENSG00000 ┆ ENSG00000 ┆ ENSG00000 ┆ … ┆ ENSG00000 ┆ ENSG00000 ┆ ENSG00000 ┆ individu │
│ 120053    ┆ 140443    ┆ 084674    ┆ 015475    ┆   ┆ 167186    ┆ 025708    ┆ 066468    ┆ al       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ -0.592022 ┆ 2.477856  ┆ 0.354833  ┆ 0.036147  ┆ … ┆ -0.543771 ┆ 0.47082   ┆ 0.605257  ┆ 1000107  │
│ 0.061036  ┆ -0.530447 ┆ null      ┆ -1.253191 ┆ … ┆ 0.134858  ┆ 0.403499  ┆ -0.595941 ┆ 1001193  │
│ 0.228713  ┆ 1.297618  ┆ -0.425314 ┆ -0.576221 ┆ … ┆ 0.68994   ┆ -0.900913 ┆ 1.088444  ┆ 1001694  │
│ 0.674837  ┆ null      ┆ -1.180707 ┆ -1.542909 ┆ … ┆ 0.511896  ┆ -0.020851 ┆ 0.012056  ┆ 1001715  │
│ 1.153924  ┆ 0.184579  ┆ 0.169054  ┆ -0.94747  ┆ … ┆ 2.311388  ┆ 0.031901  ┆ 1.788948  ┆ 1002486  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ -0.491464 ┆ -1.242181 ┆ -0.485032 ┆ -0.047356 ┆ … ┆ -0.120259 ┆ null      ┆ 0.72708   ┆ 6019565  │
│ 0.308539  ┆ -0.150795 ┆ 0.662787  ┆ -0.508696 ┆ … ┆ -0.267713 ┆ null      ┆ -0.327369 ┆ 6019855  │
│ null      ┆ -1.1371   ┆ null      ┆ 0.87775   ┆ … ┆ null      ┆ 0.845785  ┆ 0.991073  ┆ 6021528  │
│ null      ┆ 1.816509  ┆ null      ┆ 0.451261  ┆ … ┆ null      ┆ 0.458587  ┆ -1.81022  ┆ 6022842  │
│ -1.338952 ┆ 1.345314  ┆ 0.652919  ┆ 0.343063  ┆ … ┆ null      ┆ -0.805801 ┆ 1.16358   ┆ 6023199  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
pdf_lazy = (
            p_wide_lazy.unpivot(
                index=['individual'],
                on=pheno_cols,
                variable_name='phenotype',
                value_name='pheno_value',
            )
            .with_columns(
                pl.col('phenotype').str.replace('_residual', '').alias('phenotype')
            )
        )

In [ ]:
# Step A: Create a lookup dictionary mapping each ID in the large array
# to its original index. This takes O(N) time, where N is the size of sample_ids.
olink_sids = olink_lazy['individual'].to_numpy()
sample_id_to_index = {sid: i for i, sid in enumerate(sample_ids)}
print("Built a lookup dictionary for faster searching.")

# Step B: Iterate through the smaller array and find the index for each
# element if it exists in our lookup dictionary. This takes O(M) time,
# where M is the size of olink_sids.
found_indices = []
for sid in olink_sids:
    if sid in sample_id_to_index:
        found_indices.append(sample_id_to_index[sid])
print(f"Found {len(found_indices)} matching IDs.")

# Step C: Convert the list of indices to a NumPy array and sort it.
# Sorting ensures the output is identical to the original np.where approach,
# which returns indices in ascending order.
olink_indices = np.sort(found_indices)
olink_indices

Built a lookup dictionary for faster searching.
Found 40398 matching IDs.

array([    17,     23,     45, ..., 490517, 490532, 490535],
      shape=(40398,))

In [54]:
sample_ids[olink_indices]

array(['5102203', '3741733', '4072771', ..., '5141119', '5145210',
       '5733954'], shape=(40398,), dtype=StringDType())

In [58]:
len(set(olink_lazy['individual'].to_list()).intersection(set(sample_ids[olink_indices])))

40398

In [53]:
geno[:5, olink_indices]

array([[[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]]], shape=(5, 40398, 2), dtype=int8)