In [31]:
import os
import gc
import zarr
import yaml
import json
import numba
import numpy as np
import polars as pl
import pandas as pd
from tqdm import tqdm
import statsmodels.api as sm

from plotnine import *
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

from anngeno import AnnGeno
# pl.Config.set_tbl_rows(15)

In [32]:
# Configuration and paths
or_threshold_pheno = 0.99
or_threshold_anno = 0.99

eur_samples_path = '/home/dnanexus/data_dir/unrelated_cauc_samples_3rd_degree.csv'

maf=1e-3
n = !wc -l $eur_samples_path
n_eur = int(n[0].split(' ')[0])
mac = maf*(2*n_eur)

config_path = "/home/dnanexus/ukbgym/config_wgs.yaml"
with open(config_path) as f:
    config = yaml.safe_load(f)

# Read the variant consequence configuration
records = []
for group, consequences in config["variant_consequences"].items():
    for consequence in consequences:
        records.append({'variant_class': group, 'vep_consequence': consequence})
var_cons = pl.DataFrame(records)


# Use a list comprehension to flatten the nested dictionary into records
records = [
    {
        "category": category,
        "annotation": anno,
        "color": props["color"],
        "label": props["label"],
        "annotation_dir": props.get("direction", 1),
    }
    for category, annos in config["rare_variant_annotations"].items()
    for anno, props in annos.items()
]

# Create the DataFrame directly from the list of records
anno_config_df = pl.DataFrame(records)
all_annotation_list = anno_config_df.select(pl.col("annotation")).to_series().to_list()

anno_config_df

shape: (15, 5)
┌───────────────────┬──────────────────────────────┬─────────┬─────────────────┬────────────────┐
│ category          ┆ annotation                   ┆ color   ┆ label           ┆ annotation_dir │
│ ---               ┆ ---                          ┆ ---     ┆ ---             ┆ ---            │
│ str               ┆ str                          ┆ str     ┆ str             ┆ i64            │
╞═══════════════════╪══════════════════════════════╪═════════╪═════════════════╪════════════════╡
│ plof              ┆ loftee_hc                    ┆ #1f77b4 ┆ LOFTEE HC       ┆ 1              │
│ missense          ┆ am_pathogenicity             ┆ #feb72d ┆ AlphaMissense   ┆ 1              │
│ missense          ┆ esmscoremissense             ┆ #feb72d ┆ ESM1v           ┆ -1             │
│ genetic_diversity ┆ cadd_raw                     ┆ #1f77b4 ┆ CADD Raw        ┆ 1              │
│ conservation      ┆ gpn_star_llr_calibrated_mean ┆ #942c80 ┆ GPN-Star        ┆ -1             │
│ …                 ┆ …                            ┆ …       ┆ …               ┆ …              │
│ splicing          ┆ absplice_dna_max             ┆ #28a745 ┆ AbSplice (max)  ┆ 1              │
│ splicing          ┆ absplice2_max                ┆ #28a745 ┆ AbSplice2 (max) ┆ 1              │
│ regulatory_nondir ┆ promoterai_abs               ┆ #00A99D ┆ PromoterAI abs  ┆ 1              │
│ regulatory_nondir ┆ abexp_min                    ┆ #00A99D ┆ AbExp min       ┆ -1             │
│ regulatory        ┆ promoterai                   ┆ #00A99D ┆ PromoterAI      ┆ 1              │
└───────────────────┴──────────────────────────────┴─────────┴─────────────────┴────────────────┘

In [ ]:
anno = pl.scan_parquet("/home/dnanexus/data_dir/genebass394genes_olink371genes_variants_union_annotated_250928.parquet")

# existing_annos = [c for c in all_annotation_list if c in anno.collect_schema().names()]

existing_annos = ['loftee_hc', 'am_pathogenicity']

# Filter variant classes
variant_class = "coding"
consequences_for_group = var_cons.filter(
    pl.col('variant_class') == variant_class
)['vep_consequence'].to_list()
filter_expression = pl.any_horizontal(
    (pl.col(c) == 1) for c in consequences_for_group if c in anno.collect_schema().names()
)

min_range = -2000
max_range = +0

anno = (
    anno
    .filter(
        # (
        #     (pl.col('consequence_missense_variant') == 1) |
        #     (pl.col('consequence_start_lost') == 1) |
        #     (pl.col('consequence_stop_gained') == 1) |
        #     (pl.col('consequence_stop_lost') == 1) |
        #     (pl.col('consequence_splice_donor_variant') == 1) |
        #     (pl.col('consequence_splice_acceptor_variant') == 1)
        # ) &
        
        # Only SNPs
        (pl.col('ref').str.len_chars()==1) & (pl.col('alt').str.len_chars()==1)
    )
    .select(
        set(['id', 'region', 'TSS', 'Strand', 'gene_length', 'gene_name', 'dist_to_tss']).union(set(existing_annos))
    )
    .collect(engine='streaming')
    # .drop_nulls()
)

anno

shape: (22_836_054, 9)
┌───────────┬────────────┬────────────┬───────────┬───┬────────┬───────────┬───────────┬───────────┐
│ gene_name ┆ id         ┆ am_pathoge ┆ loftee_hc ┆ … ┆ Strand ┆ dist_to_t ┆ region    ┆ TSS       │
│ ---       ┆ ---        ┆ nicity     ┆ ---       ┆   ┆ ---    ┆ ss        ┆ ---       ┆ ---       │
│ str       ┆ str        ┆ ---        ┆ i8        ┆   ┆ cat    ┆ ---       ┆ str       ┆ i64       │
│           ┆            ┆ f32        ┆           ┆   ┆        ┆ i64       ┆           ┆           │
╞═══════════╪════════════╪════════════╪═══════════╪═══╪════════╪═══════════╪═══════════╪═══════════╡
│ LRP2      ┆ chr2:16919 ┆ 0.0        ┆ 0         ┆ … ┆ -      ┆ 165367    ┆ ENSG00000 ┆ 169362534 │
│           ┆ 7167:T:G   ┆            ┆           ┆   ┆        ┆           ┆ 081479    ┆           │
│ LRP2      ┆ chr2:16920 ┆ 0.0        ┆ 0         ┆ … ┆ -      ┆ 158242    ┆ ENSG00000 ┆ 169362534 │
│           ┆ 4292:A:T   ┆            ┆           ┆   ┆        ┆           ┆ 081479    ┆           │
│ ABCB11    ┆ chr2:16903 ┆ 0.0        ┆ 0         ┆ … ┆ -      ┆ 793       ┆ ENSG00000 ┆ 169031324 │
│           ┆ 0531:C:T   ┆            ┆           ┆   ┆        ┆           ┆ 073734    ┆           │
│ ABCB11    ┆ chr2:16891 ┆ 0.0        ┆ 0         ┆ … ┆ -      ┆ 120499    ┆ ENSG00000 ┆ 169031324 │
│           ┆ 0825:T:G   ┆            ┆           ┆   ┆        ┆           ┆ 073734    ┆           │
│ ABCB11    ┆ chr2:16896 ┆ 0.0607     ┆ 0         ┆ … ┆ -      ┆ 61780     ┆ ENSG00000 ┆ 169031324 │
│           ┆ 9544:T:C   ┆            ┆           ┆   ┆        ┆           ┆ 073734    ┆           │
│ …         ┆ …          ┆ …          ┆ …         ┆ … ┆ …      ┆ …         ┆ …         ┆ …         │
│ GCKR      ┆ chr2:27526 ┆ 0.0        ┆ 0         ┆ … ┆ +      ┆ 29323     ┆ ENSG00000 ┆ 27496838  │
│           ┆ 161:C:A    ┆            ┆           ┆   ┆        ┆           ┆ 084734    ┆           │
│ GCKR      ┆ chr2:27524 ┆ 0.0        ┆ 0         ┆ … ┆ +      ┆ 28041     ┆ ENSG00000 ┆ 27496838  │
│           ┆ 879:T:C    ┆            ┆           ┆   ┆        ┆           ┆ 084734    ┆           │
│ TRIM40    ┆ chr6:30150 ┆ 0.0        ┆ 0         ┆ … ┆ +      ┆ 14610     ┆ ENSG00000 ┆ 30136123  │
│           ┆ 733:A:C    ┆            ┆           ┆   ┆        ┆           ┆ 204614    ┆           │
│ SETX      ┆ chr9:13235 ┆ 0.0        ┆ 0         ┆ … ┆ -      ┆ -3584     ┆ ENSG00000 ┆ 132354986 │
│           ┆ 8570:C:A   ┆            ┆           ┆   ┆        ┆           ┆ 107290    ┆           │
│ BCL7A     ┆ chr12:1220 ┆ 0.0        ┆ 0         ┆ … ┆ +      ┆ 46026     ┆ ENSG00000 ┆ 122019421 │
│           ┆ 65447:G:A  ┆            ┆           ┆   ┆        ┆           ┆ 110987    ┆           │
└───────────┴────────────┴────────────┴───────────┴───┴────────┴───────────┴───────────┴───────────┘

In [34]:
melted_anno = (
    anno
    .with_columns(
        am_pathogenicity = pl.col('am_pathogenicity') >= 0.8
    )

    .unpivot(
        index=["id", "region"],
        on=existing_annos,
        variable_name="annotation",
        value_name="annotation_score"
    )
    .with_columns(
        pl.col("annotation_score").cast(pl.Float32),
        pl.col("region").cast(pl.Utf8),
    )

    # Merge with annotation configuration to get direction and filter
    .join(
        anno_config_df,
        on="annotation",
        how="left"
    )
    .with_columns(
        annotation_score_dircor = pl.col('annotation_score') * pl.col("annotation_dir")
    )
)

melted_anno

shape: (45_672_108, 9)
┌────────────┬───────────┬───────────┬───────────┬───┬─────────┬───────────┬───────────┬───────────┐
│ id         ┆ region    ┆ annotatio ┆ annotatio ┆ … ┆ color   ┆ label     ┆ annotatio ┆ annotatio │
│ ---        ┆ ---       ┆ n         ┆ n_score   ┆   ┆ ---     ┆ ---       ┆ n_dir     ┆ n_score_d │
│ str        ┆ str       ┆ ---       ┆ ---       ┆   ┆ str     ┆ str       ┆ ---       ┆ ircor     │
│            ┆           ┆ str       ┆ f32       ┆   ┆         ┆           ┆ i64       ┆ ---       │
│            ┆           ┆           ┆           ┆   ┆         ┆           ┆           ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════╪═══════════╪═══════════╪═══════════╡
│ chr2:16919 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #1f77b4 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 7167:T:G   ┆ 081479    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ chr2:16920 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #1f77b4 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 4292:A:T   ┆ 081479    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ chr2:16903 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #1f77b4 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 0531:C:T   ┆ 073734    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ chr2:16891 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #1f77b4 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 0825:T:G   ┆ 073734    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ chr2:16896 ┆ ENSG00000 ┆ loftee_hc ┆ 0.0       ┆ … ┆ #1f77b4 ┆ LOFTEE HC ┆ 1         ┆ 0.0       │
│ 9544:T:C   ┆ 073734    ┆           ┆           ┆   ┆         ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …       ┆ …         ┆ …         ┆ …         │
│ chr2:27526 ┆ ENSG00000 ┆ am_pathog ┆ 0.0       ┆ … ┆ #feb72d ┆ AlphaMiss ┆ 1         ┆ 0.0       │
│ 161:C:A    ┆ 084734    ┆ enicity   ┆           ┆   ┆         ┆ ense      ┆           ┆           │
│ chr2:27524 ┆ ENSG00000 ┆ am_pathog ┆ 0.0       ┆ … ┆ #feb72d ┆ AlphaMiss ┆ 1         ┆ 0.0       │
│ 879:T:C    ┆ 084734    ┆ enicity   ┆           ┆   ┆         ┆ ense      ┆           ┆           │
│ chr6:30150 ┆ ENSG00000 ┆ am_pathog ┆ 0.0       ┆ … ┆ #feb72d ┆ AlphaMiss ┆ 1         ┆ 0.0       │
│ 733:A:C    ┆ 204614    ┆ enicity   ┆           ┆   ┆         ┆ ense      ┆           ┆           │
│ chr9:13235 ┆ ENSG00000 ┆ am_pathog ┆ 0.0       ┆ … ┆ #feb72d ┆ AlphaMiss ┆ 1         ┆ 0.0       │
│ 8570:C:A   ┆ 107290    ┆ enicity   ┆           ┆   ┆         ┆ ense      ┆           ┆           │
│ chr12:1220 ┆ ENSG00000 ┆ am_pathog ┆ 0.0       ┆ … ┆ #feb72d ┆ AlphaMiss ┆ 1         ┆ 0.0       │
│ 65447:G:A  ┆ 110987    ┆ enicity   ┆           ┆   ┆         ┆ ense      ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴─────────┴───────────┴───────────┴───────────┘

In [35]:
melted_anno.select(['id', 'annotation', 'annotation_score']).unique().filter(pl.col('annotation') == 'loftee_hc').select('annotation_score').sum()

shape: (1, 1)
┌──────────────────┐
│ annotation_score │
│ ---              │
│ f32              │
╞══════════════════╡
│ 21519.0          │
└──────────────────┘

In [36]:
melted_anno.select(['id', 'annotation', 'annotation_score']).unique().filter(pl.col('annotation') == 'am_pathogenicity').select('annotation_score').sum()

shape: (1, 1)
┌──────────────────┐
│ annotation_score │
│ ---              │
│ f32              │
╞══════════════════╡
│ 56609.0          │
└──────────────────┘

In [37]:
appv = pl.scan_parquet("/home/dnanexus/data_dir/appv_files/avg_pheno_per_var_quantitative_EUR_genebass1e6_PRScorr_with_percentiles.parquet")

# Create a lazy frame with the unique keys
anno_keys = anno.select(pl.col('id').unique()).lazy()

# Chain the filter and the much faster semi join
appv = (
    appv
        .join(
        anno_keys, on='id', how='semi'
    )
    .filter(
        pl.col('n_individuals') <= mac
    )
    .select(
        ['id', 'phenotype', 'mean_pheno_value_ptile', 'n_individuals']
    )
)

# unique_phenotypes = appv.select('phenotype').unique().collect(engine='streaming').to_series()

In [38]:
# Get gene trait associations

plof = pl.read_parquet('/home/dnanexus/data_dir/association_files/rvat_EUR_500k_regenie.parquet').with_columns(
    phenotype = (pl.col('trait') + '_int'),
    region = pl.col('gene_id'),
    rvat_pval = (10** -pl.col("neg_log10p")),
).filter(
    (pl.col('trait_type') == 'quantitative')
)

loftee_corr = pl.read_parquet("/home/dnanexus/data_dir/association_files/loftee_correlation_quantitative_wgs_EUR_genebass1e6_maf1e3_snp_consistent.parquet")

gene_trait_df = loftee_corr.join(plof[['region', 'phenotype', 'beta', 'rvat_pval']], on=['region', 'phenotype'], how='inner').filter(
    pl.col('loftee_corr')*pl.col('beta') > 0
).with_columns(
    corr_dir = pl.col('loftee_corr')/pl.col('loftee_corr').abs()
)

# gene_trait_df = gene_trait_df.head()
gene_trait_df

shape: (1_176, 8)
┌────────────┬───────────┬────────────┬────────────┬────────────┬───────────┬───────────┬──────────┐
│ region     ┆ gene_name ┆ phenotype  ┆ loftee_cor ┆ n_variants ┆ beta      ┆ rvat_pval ┆ corr_dir │
│ ---        ┆ ---       ┆ ---        ┆ r          ┆ ---        ┆ ---       ┆ ---       ┆ ---      │
│ str        ┆ str       ┆ str        ┆ ---        ┆ u64        ┆ f64       ┆ f64       ┆ f64      │
│            ┆           ┆            ┆ f64        ┆            ┆           ┆           ┆          │
╞════════════╪═══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪══════════╡
│ ENSG000001 ┆ PAPPA2    ┆ arm_fatfre ┆ -0.014747  ┆ 82603      ┆ -0.195409 ┆ 9.1637e-8 ┆ -1.0     │
│ 16183      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ COPB1     ┆ arm_fatfre ┆ -0.014338  ┆ 13594      ┆ -0.397279 ┆ 0.006626  ┆ -1.0     │
│ 29083      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ KIAA0586  ┆ arm_fatfre ┆ -0.010787  ┆ 28541      ┆ -0.058463 ┆ 0.000305  ┆ -1.0     │
│ 00578      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ ACAN      ┆ arm_fatfre ┆ -0.036259  ┆ 20244      ┆ -0.436618 ┆ 6.0395e-1 ┆ -1.0     │
│ 57766      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆ 1         ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ IGF1R     ┆ arm_fatfre ┆ -0.013644  ┆ 82469      ┆ -0.412619 ┆ 2.8609e-8 ┆ -1.0     │
│ 40443      ┆           ┆ e_mass_rig ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ ht_int     ┆            ┆            ┆           ┆           ┆          │
│ …          ┆ …         ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …        │
│ ENSG000001 ┆ RHAG      ┆ reticulocy ┆ 0.033239   ┆ 9849       ┆ 0.952411  ┆ 1.8038e-4 ┆ 1.0      │
│ 12077      ┆           ┆ te_count_i ┆            ┆            ┆           ┆ 1         ┆          │
│            ┆           ┆ nt         ┆            ┆            ┆           ┆           ┆          │
│ ENSG000000 ┆ ANK1      ┆ reticulocy ┆ 0.02685    ┆ 54620      ┆ 0.656849  ┆ 2.1682e-1 ┆ 1.0      │
│ 29534      ┆           ┆ te_count_i ┆            ┆            ┆           ┆ 0         ┆          │
│            ┆           ┆ nt         ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ VPS13A    ┆ reticulocy ┆ 0.003971   ┆ 55477      ┆ 0.176348  ┆ 2.1188e-7 ┆ 1.0      │
│ 97969      ┆           ┆ te_count_i ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ nt         ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ LRP5      ┆ heel_bone_ ┆ -0.024278  ┆ 21119      ┆ -0.794196 ┆ 5.5055e-1 ┆ -1.0     │
│ 62337      ┆           ┆ mineral_de ┆            ┆            ┆           ┆ 0         ┆          │
│            ┆           ┆ nsity_bmd_ ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ …          ┆            ┆            ┆           ┆           ┆          │
│ ENSG000001 ┆ SMAD6     ┆ heel_bone_ ┆ -0.029893  ┆ 12754      ┆ -0.43297  ┆ 0.000005  ┆ -1.0     │
│ 37834      ┆           ┆ mineral_de ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ nsity_bmd_ ┆            ┆            ┆           ┆           ┆          │
│            ┆           ┆ …          ┆            ┆            ┆           ┆           ┆          │
└────────────┴───────────┴────────────┴────────────┴────────────┴───────────┴───────────┴──────────┘

In [39]:
gene_trait_df['region'].n_unique(), gene_trait_df.shape[0]

(352, 1176)

In [40]:
# --- 1. Lazily prepare the filter keys ---
region_keys = gene_trait_df.lazy().select(pl.col('region').unique())
anno_ids_lazy = melted_anno.lazy().join(
    region_keys, on='region', how='semi'
).select(pl.col('id').unique())


# --- Build main query (same as before, but stop before group_by) ---
gp_lazy = (
    appv
    .join(anno_ids_lazy, on="id", how="semi")
    .join(
        melted_anno.lazy().drop([c for c in melted_anno.columns if 'is_nan' in c]), 
        on="id", 
        how="inner"
    )
    .join(
        gene_trait_df.lazy(), 
        on=["region", "phenotype"], 
        how="inner"
    )
    .with_columns(
        mean_pheno_value_dircor_ptile = pl.col('mean_pheno_value_ptile') * pl.col('loftee_corr')
    )
    
    .group_by(["annotation", "region", "gene_name", "phenotype"])
    .agg(
        n_dis_above_cutoff = ((pl.col("annotation_score_dircor")==1) & (pl.col("mean_pheno_value_dircor_ptile") >= or_threshold_pheno)).sum(),
        n_notdis_above_cutoff = ((pl.col("annotation_score_dircor")==1) & (pl.col("mean_pheno_value_dircor_ptile") < or_threshold_pheno)).sum()
    )
    .with_columns(
        odds_ratio = ((pl.col("n_dis_above_cutoff") + 1) / (pl.col("n_notdis_above_cutoff")+1)) / (1 - or_threshold_pheno)
    )
)

# Execute
print("Executing with odds ratios...")
or_df = gp_lazy.collect(engine='streaming')
or_df

Executing with odds ratios...

shape: (2_352, 7)
┌──────────────┬──────────────┬───────────┬──────────────┬──────────────┬─────────────┬────────────┐
│ annotation   ┆ region       ┆ gene_name ┆ phenotype    ┆ n_dis_above_ ┆ n_notdis_ab ┆ odds_ratio │
│ ---          ┆ ---          ┆ ---       ┆ ---          ┆ cutoff       ┆ ove_cutoff  ┆ ---        │
│ str          ┆ str          ┆ str       ┆ str          ┆ ---          ┆ ---         ┆ f64        │
│              ┆              ┆           ┆              ┆ u64          ┆ u64         ┆            │
╞══════════════╪══════════════╪═══════════╪══════════════╪══════════════╪═════════════╪════════════╡
│ loftee_hc    ┆ ENSG00000127 ┆ FBXL16    ┆ arm_fat_perc ┆ 0            ┆ 4           ┆ 20.0       │
│              ┆ 585          ┆           ┆ entage_right ┆              ┆             ┆            │
│              ┆              ┆           ┆ _int         ┆              ┆             ┆            │
│ am_pathogeni ┆ ENSG00000187 ┆ TMPRSS6   ┆ haemoglobin_ ┆ 0            ┆ 0           ┆ 100.0      │
│ city         ┆ 045          ┆           ┆ concentratio ┆              ┆             ┆            │
│              ┆              ┆           ┆ n_int        ┆              ┆             ┆            │
│ am_pathogeni ┆ ENSG00000087 ┆ CETP      ┆ apolipoprote ┆ 0            ┆ 7           ┆ 12.5       │
│ city         ┆ 237          ┆           ┆ in_a_int     ┆              ┆             ┆            │
│ am_pathogeni ┆ ENSG00000065 ┆ PACC1     ┆ sitting_heig ┆ 0            ┆ 20          ┆ 4.761905   │
│ city         ┆ 600          ┆           ┆ ht_int       ┆              ┆             ┆            │
│ am_pathogeni ┆ ENSG00000136 ┆ ANGPTL2   ┆ standing_hei ┆ 0            ┆ 68          ┆ 1.449275   │
│ city         ┆ 859          ┆           ┆ ght_int      ┆              ┆             ┆            │
│ …            ┆ …            ┆ …         ┆ …            ┆ …            ┆ …           ┆ …          │
│ am_pathogeni ┆ ENSG00000145 ┆ TIMD4     ┆ cholesterol_ ┆ 0            ┆ 17          ┆ 5.555556   │
│ city         ┆ 850          ┆           ┆ int          ┆              ┆             ┆            │
│ am_pathogeni ┆ ENSG00000236 ┆ SLFN14    ┆ mean_platele ┆ 0            ┆ 15          ┆ 6.25       │
│ city         ┆ 320          ┆           ┆ t_thrombocyt ┆              ┆             ┆            │
│              ┆              ┆           ┆ e_volu…      ┆              ┆             ┆            │
│ am_pathogeni ┆ ENSG00000118 ┆ ABCG2     ┆ urate_int    ┆ 0            ┆ 65          ┆ 1.515152   │
│ city         ┆ 777          ┆           ┆              ┆              ┆             ┆            │
│ am_pathogeni ┆ ENSG00000118 ┆ PKD2      ┆ urea_int     ┆ 0            ┆ 42          ┆ 2.325581   │
│ city         ┆ 762          ┆           ┆              ┆              ┆             ┆            │
│ am_pathogeni ┆ ENSG00000101 ┆ LIPG      ┆ apolipoprote ┆ 0            ┆ 29          ┆ 3.333333   │
│ city         ┆ 670          ┆           ┆ in_a_int     ┆              ┆             ┆            │
└──────────────┴──────────────┴───────────┴──────────────┴──────────────┴─────────────┴────────────┘

In [41]:
plt_df = (
    or_df
    .drop_nans()
    .with_columns(
        n_gene_phenos = pl.len().over('annotation'),
        avg_odds_ratio = pl.col('odds_ratio').mean().over('annotation'),
        std_odds_ratio = pl.col('odds_ratio').std().over('annotation'),
    )
    .with_columns(
        std_ci_upper = pl.col('avg_odds_ratio') + 1.96 * (pl.col('std_odds_ratio')),
        std_ci_lower = pl.col('avg_odds_ratio') - 1.96 * (pl.col('std_odds_ratio')),
    )
    .select(['annotation', 'n_gene_phenos', 'avg_odds_ratio', 'std_odds_ratio', 'std_ci_upper', 'std_ci_lower'])
    .unique()
)
plt_df

shape: (2, 6)
┌──────────────────┬───────────────┬────────────────┬────────────────┬──────────────┬──────────────┐
│ annotation       ┆ n_gene_phenos ┆ avg_odds_ratio ┆ std_odds_ratio ┆ std_ci_upper ┆ std_ci_lower │
│ ---              ┆ ---           ┆ ---            ┆ ---            ┆ ---          ┆ ---          │
│ str              ┆ u64           ┆ f64            ┆ f64            ┆ f64          ┆ f64          │
╞══════════════════╪═══════════════╪════════════════╪════════════════╪══════════════╪══════════════╡
│ am_pathogenicity ┆ 1176          ┆ 8.966652       ┆ 23.514658      ┆ 55.055382    ┆ -37.122078   │
│ loftee_hc        ┆ 1176          ┆ 6.735885       ┆ 7.426953       ┆ 21.292713    ┆ -7.820942    │
└──────────────────┴───────────────┴────────────────┴────────────────┴──────────────┴──────────────┘

In [13]:
plt_df = (
    or_df
    .drop_nans()
    .with_columns(
        n_gene_phenos = pl.len().over('annotation'),
        avg_odds_ratio = pl.col('odds_ratio').mean().over('annotation'),
        std_odds_ratio = pl.col('odds_ratio').std().over('annotation'),
    )
    .with_columns(
        std_ci_upper = pl.col('avg_odds_ratio') + 1.96 * (pl.col('std_odds_ratio')),
        std_ci_lower = pl.col('avg_odds_ratio') - 1.96 * (pl.col('std_odds_ratio')),
    )
    .select(['annotation', 'n_gene_phenos', 'avg_odds_ratio', 'std_odds_ratio', 'std_ci_upper', 'std_ci_lower'])
    .unique()
)
plt_df

shape: (2, 6)
┌──────────────────┬───────────────┬────────────────┬────────────────┬──────────────┬──────────────┐
│ annotation       ┆ n_gene_phenos ┆ avg_odds_ratio ┆ std_odds_ratio ┆ std_ci_upper ┆ std_ci_lower │
│ ---              ┆ ---           ┆ ---            ┆ ---            ┆ ---          ┆ ---          │
│ str              ┆ u64           ┆ f64            ┆ f64            ┆ f64          ┆ f64          │
╞══════════════════╪═══════════════╪════════════════╪════════════════╪══════════════╪══════════════╡
│ loftee_hc        ┆ 1176          ┆ 6.735885       ┆ 7.426953       ┆ 21.292713    ┆ -7.820942    │
│ am_pathogenicity ┆ 1176          ┆ 8.966652       ┆ 23.514658      ┆ 55.055382    ┆ -37.122078   │
└──────────────────┴───────────────┴────────────────┴────────────────┴──────────────┴──────────────┘