In [1]:
import polars as pl
import pandas as pd
import pyranges as pr

/opt/modules/i12g/anaconda/envs/sl-ukg/lib/python3.12/site-packages/sorted_nearest/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [2]:
anno_sub = pl.read_parquet('/s/project/deeprvat/ukb_gym/var_lists/ukbgym_variants_snps_dms_251001.parquet')
anno_sub

shape: (582_174, 6)
┌────────────────────┬─────────────────┬───────┬──────────┬─────┬─────┐
│ id                 ┆ gene_id         ┆ chrom ┆ pos      ┆ ref ┆ alt │
│ ---                ┆ ---             ┆ ---   ┆ ---      ┆ --- ┆ --- │
│ str                ┆ str             ┆ str   ┆ i32      ┆ str ┆ str │
╞════════════════════╪═════════════════╪═══════╪══════════╪═════╪═════╡
│ chr1:1320456:C:T   ┆ ENSG00000127054 ┆ chr1  ┆ 1320456  ┆ C   ┆ T   │
│ chr1:1320460:T:C   ┆ ENSG00000127054 ┆ chr1  ┆ 1320460  ┆ T   ┆ C   │
│ chr1:1320468:C:G   ┆ ENSG00000127054 ┆ chr1  ┆ 1320468  ┆ C   ┆ G   │
│ chr1:1320476:G:C   ┆ ENSG00000127054 ┆ chr1  ┆ 1320476  ┆ G   ┆ C   │
│ chr1:1320479:G:A   ┆ ENSG00000127054 ┆ chr1  ┆ 1320479  ┆ G   ┆ A   │
│ …                  ┆ …               ┆ …     ┆ …        ┆ …   ┆ …   │
│ chr22:42912069:T:C ┆ ENSG00000100266 ┆ chr22 ┆ 42912069 ┆ T   ┆ C   │
│ chr22:42912072:G:A ┆ ENSG00000100266 ┆ chr22 ┆ 42912072 ┆ G   ┆ A   │
│ chr22:42912072:G:C ┆ ENSG00000100266 ┆ chr22 ┆ 42912072 ┆ G   ┆ C   │
│ chr22:42912077:A:G ┆ ENSG00000100266 ┆ chr22 ┆ 42912077 ┆ A   ┆ G   │
│ chr22:42912078:C:A ┆ ENSG00000100266 ┆ chr22 ┆ 42912078 ┆ C   ┆ A   │
└────────────────────┴─────────────────┴───────┴──────────┴─────┴─────┘

In [3]:
# Path to your GENCODE GTF file
gtf_path = "/s/project/deeprvat/ukb_gym/gencode/gencode.v49.annotation.gtf.gz"

# Read GTF and filter for transcripts
gencode_pr = pr.read_gtf(gtf_path)
gencode_pr

+--------------+------------+------------+-----------+-----------+-------+
| Chromosome   | Source     | Feature    | Start     | End       | +21   |
| (category)   | (object)   | (object)   | (int64)   | (int64)   | ...   |
|--------------+------------+------------+-----------+-----------+-------|
| chr1         | HAVANA     | gene       | 11120     | 24894     | ...   |
| chr1         | HAVANA     | transcript | 11120     | 14413     | ...   |
| chr1         | HAVANA     | exon       | 11120     | 11211     | ...   |
| chr1         | HAVANA     | exon       | 12009     | 12227     | ...   |
| ...          | ...        | ...        | ...       | ...       | ...   |
| chrY         | HAVANA     | exon       | 57213879  | 57213964  | ...   |
| chrY         | HAVANA     | exon       | 57213525  | 57213602  | ...   |
| chrY         | HAVANA     | exon       | 57213203  | 57213357  | ...   |
| chrY         | HAVANA     | exon       | 57212183  | 57213125  | ...   |
+--------------+------------+------------+-----------+-----------+-------+
Stranded PyRanges object has 7,750,154 rows and 26 columns from 25 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
21 hidden columns: Score, Strand, Frame, gene_id, gene_type, gene_name, level, ... (+ 14 more.)

In [4]:
gencode_pr.df['Feature'].unique()

array(['gene', 'transcript', 'exon', 'CDS', 'start_codon', 'stop_codon',
       'UTR', 'Selenocysteine'], dtype=object)

In [5]:
gpl = pl.from_pandas(gencode_pr.df)

filt_gpl = gpl.filter(
    (pl.col('transcript_type') == 'protein_coding') |
    (pl.col('transcript_type').str.contains('pseudogene')) |
    (pl.col('Feature') == 'CDS')
).filter(
    pl.col('Feature') != 'transcript'
)
filt_gpl

shape: (5_697_083, 26)
┌────────────┬────────┬─────────┬──────────┬───┬─────────────┬────────────┬────────┬────────────┐
│ Chromosome ┆ Source ┆ Feature ┆ Start    ┆ … ┆ ont         ┆ protein_id ┆ ccdsid ┆ artif_dupl │
│ ---        ┆ ---    ┆ ---     ┆ ---      ┆   ┆ ---         ┆ ---        ┆ ---    ┆ ---        │
│ cat        ┆ str    ┆ str     ┆ i64      ┆   ┆ str         ┆ str        ┆ str    ┆ str        │
╞════════════╪════════╪═════════╪══════════╪═══╪═════════════╪════════════╪════════╪════════════╡
│ chr1       ┆ HAVANA ┆ exon    ┆ 12009    ┆ … ┆ PGO:0000019 ┆ null       ┆ null   ┆ null       │
│ chr1       ┆ HAVANA ┆ exon    ┆ 12178    ┆ … ┆ PGO:0000019 ┆ null       ┆ null   ┆ null       │
│ chr1       ┆ HAVANA ┆ exon    ┆ 12612    ┆ … ┆ PGO:0000019 ┆ null       ┆ null   ┆ null       │
│ chr1       ┆ HAVANA ┆ exon    ┆ 12974    ┆ … ┆ PGO:0000019 ┆ null       ┆ null   ┆ null       │
│ chr1       ┆ HAVANA ┆ exon    ┆ 13220    ┆ … ┆ PGO:0000019 ┆ null       ┆ null   ┆ null       │
│ …          ┆ …      ┆ …       ┆ …        ┆ … ┆ …           ┆ …          ┆ …      ┆ …          │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57214349 ┆ … ┆ PGO:0000005 ┆ null       ┆ null   ┆ null       │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57213879 ┆ … ┆ PGO:0000005 ┆ null       ┆ null   ┆ null       │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57213525 ┆ … ┆ PGO:0000005 ┆ null       ┆ null   ┆ null       │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57213203 ┆ … ┆ PGO:0000005 ┆ null       ┆ null   ┆ null       │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57212183 ┆ … ┆ PGO:0000005 ┆ null       ┆ null   ┆ null       │
└────────────┴────────┴─────────┴──────────┴───┴─────────────┴────────────┴────────┴────────────┘

In [6]:
filt_gpl['transcript_type'].value_counts(sort=True)

shape: (26, 2)
┌─────────────────────────────────┬─────────┐
│ transcript_type                 ┆ count   │
│ ---                             ┆ ---     │
│ str                             ┆ u32     │
╞═════════════════════════════════╪═════════╡
│ protein_coding                  ┆ 5550761 │
│ nonsense_mediated_decay         ┆ 115666  │
│ processed_pseudogene            ┆ 10974   │
│ transcribed_unprocessed_pseudo… ┆ 9036    │
│ unprocessed_pseudogene          ┆ 4613    │
│ …                               ┆ …       │
│ TR_D_gene                       ┆ 5       │
│ TR_J_pseudogene                 ┆ 4       │
│ IG_J_pseudogene                 ┆ 3       │
│ translated_processed_pseudogen… ┆ 2       │
│ IG_pseudogene                   ┆ 1       │
└─────────────────────────────────┴─────────┘

In [7]:
filt_gpl['gene_type'].value_counts(sort=True)

shape: (23, 2)
┌─────────────────────────────────┬─────────┐
│ gene_type                       ┆ count   │
│ ---                             ┆ ---     │
│ str                             ┆ u32     │
╞═════════════════════════════════╪═════════╡
│ protein_coding                  ┆ 5667691 │
│ processed_pseudogene            ┆ 10974   │
│ transcribed_unprocessed_pseudo… ┆ 9036    │
│ unprocessed_pseudogene          ┆ 4613    │
│ transcribed_unitary_pseudogene  ┆ 1485    │
│ …                               ┆ …       │
│ TR_D_gene                       ┆ 5       │
│ TR_J_pseudogene                 ┆ 4       │
│ IG_J_pseudogene                 ┆ 3       │
│ translated_processed_pseudogen… ┆ 2       │
│ IG_pseudogene                   ┆ 1       │
└─────────────────────────────────┴─────────┘

In [8]:
anti_filt_gpl = gpl.filter(
    (pl.col('transcript_type') != 'protein_coding') &
    (~pl.col('transcript_type').str.contains('pseudogene')) & 
    (pl.col('Feature') != 'CDS')
)

anti_filt_gpl

shape: (1_747_733, 26)
┌────────────┬────────┬────────────┬──────────┬───┬──────┬────────────┬────────┬────────────┐
│ Chromosome ┆ Source ┆ Feature    ┆ Start    ┆ … ┆ ont  ┆ protein_id ┆ ccdsid ┆ artif_dupl │
│ ---        ┆ ---    ┆ ---        ┆ ---      ┆   ┆ ---  ┆ ---        ┆ ---    ┆ ---        │
│ cat        ┆ str    ┆ str        ┆ i64      ┆   ┆ str  ┆ str        ┆ str    ┆ str        │
╞════════════╪════════╪════════════╪══════════╪═══╪══════╪════════════╪════════╪════════════╡
│ chr1       ┆ HAVANA ┆ transcript ┆ 11120    ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ chr1       ┆ HAVANA ┆ exon       ┆ 11120    ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ chr1       ┆ HAVANA ┆ exon       ┆ 12009    ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ chr1       ┆ HAVANA ┆ exon       ┆ 12612    ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ chr1       ┆ HAVANA ┆ exon       ┆ 13452    ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ …          ┆ …      ┆ …          ┆ …        ┆ … ┆ …    ┆ …          ┆ …      ┆ …          │
│ chrY       ┆ HAVANA ┆ exon       ┆ 57213879 ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ chrY       ┆ HAVANA ┆ exon       ┆ 57212922 ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ chrY       ┆ HAVANA ┆ transcript ┆ 57213905 ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ chrY       ┆ HAVANA ┆ exon       ┆ 57214349 ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
│ chrY       ┆ HAVANA ┆ exon       ┆ 57213905 ┆ … ┆ null ┆ null       ┆ null   ┆ null       │
└────────────┴────────┴────────────┴──────────┴───┴──────┴────────────┴────────┴────────────┘

In [9]:
filt_gpl = filt_gpl.with_columns(
    Gene = pl.col('gene_id').str.split('.').list.get(0)
)
filt_gpl

shape: (5_697_083, 27)
┌────────────┬────────┬─────────┬──────────┬───┬────────────┬────────┬────────────┬────────────────┐
│ Chromosome ┆ Source ┆ Feature ┆ Start    ┆ … ┆ protein_id ┆ ccdsid ┆ artif_dupl ┆ Gene           │
│ ---        ┆ ---    ┆ ---     ┆ ---      ┆   ┆ ---        ┆ ---    ┆ ---        ┆ ---            │
│ cat        ┆ str    ┆ str     ┆ i64      ┆   ┆ str        ┆ str    ┆ str        ┆ str            │
╞════════════╪════════╪═════════╪══════════╪═══╪════════════╪════════╪════════════╪════════════════╡
│ chr1       ┆ HAVANA ┆ exon    ┆ 12009    ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000022397 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 2              │
│ chr1       ┆ HAVANA ┆ exon    ┆ 12178    ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000022397 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 2              │
│ chr1       ┆ HAVANA ┆ exon    ┆ 12612    ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000022397 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 2              │
│ chr1       ┆ HAVANA ┆ exon    ┆ 12974    ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000022397 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 2              │
│ chr1       ┆ HAVANA ┆ exon    ┆ 13220    ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000022397 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 2              │
│ …          ┆ …      ┆ …       ┆ …        ┆ … ┆ …          ┆ …      ┆ …          ┆ …              │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57214349 ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000029237 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 1              │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57213879 ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000029237 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 1              │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57213525 ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000029237 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 1              │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57213203 ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000029237 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 1              │
│ chrY       ┆ HAVANA ┆ exon    ┆ 57212183 ┆ … ┆ null       ┆ null   ┆ null       ┆ ENSG0000029237 │
│            ┆        ┆         ┆          ┆   ┆            ┆        ┆            ┆ 1              │
└────────────┴────────┴─────────┴──────────┴───┴────────────┴────────┴────────────┴────────────────┘

In [10]:
filt_gpl['Feature'].value_counts(sort=True)

shape: (6, 2)
┌────────────────┬─────────┐
│ Feature        ┆ count   │
│ ---            ┆ ---     │
│ str            ┆ u32     │
╞════════════════╪═════════╡
│ exon           ┆ 2410438 │
│ CDS            ┆ 2283012 │
│ UTR            ┆ 607057  │
│ start_codon    ┆ 203710  │
│ stop_codon     ┆ 192747  │
│ Selenocysteine ┆ 119     │
└────────────────┴─────────┘

In [11]:
gencode_pr_cds = pr.PyRanges(filt_gpl.to_pandas())
gencode_pr_cds

+--------------+------------+------------+-----------+-----------+-------+
| Chromosome   | Source     | Feature    | Start     | End       | +22   |
| (category)   | (object)   | (object)   | (int64)   | (int64)   | ...   |
|--------------+------------+------------+-----------+-----------+-------|
| chr1         | HAVANA     | exon       | 12009     | 12057     | ...   |
| chr1         | HAVANA     | exon       | 12178     | 12227     | ...   |
| chr1         | HAVANA     | exon       | 12612     | 12697     | ...   |
| chr1         | HAVANA     | exon       | 12974     | 13052     | ...   |
| ...          | ...        | ...        | ...       | ...       | ...   |
| chrY         | HAVANA     | exon       | 57213879  | 57213964  | ...   |
| chrY         | HAVANA     | exon       | 57213525  | 57213602  | ...   |
| chrY         | HAVANA     | exon       | 57213203  | 57213357  | ...   |
| chrY         | HAVANA     | exon       | 57212183  | 57213125  | ...   |
+--------------+------------+------------+-----------+-----------+-------+
Unstranded PyRanges object has 5,697,083 rows and 27 columns from 25 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
22 hidden columns: Score, Strand, Frame, gene_id, gene_type, gene_name, level, ... (+ 15 more.)

In [12]:
gencode_coding_regions = gencode_pr_cds.merge()
gencode_coding_regions

+--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int64)   | (int64)   |
|--------------+-----------+-----------|
| chr1         | 12009     | 12057     |
| chr1         | 12178     | 12227     |
| chr1         | 12612     | 12697     |
| chr1         | 12974     | 13052     |
| ...          | ...       | ...       |
| chrY         | 57213203  | 57213357  |
| chrY         | 57213525  | 57213602  |
| chrY         | 57213879  | 57213964  |
| chrY         | 57214349  | 57214397  |
+--------------+-----------+-----------+
Unstranded PyRanges object has 269,756 rows and 3 columns from 25 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

## Annotate UKBBGym variants

In [13]:
anno = (
    pl.read_parquet(
        '/s/project/deeprvat/wgs_preprocessing_rap/annotation/genebass394genes_olink371genes_variants_union_annotated_250928.parquet', 
        columns=['id', 'chrom', 'pos', 'ref', 'alt', 'gene']
    )
    .with_columns(
        Chromosome = pl.col('chrom'),
        Start = pl.col('pos') - 1,
        End = pl.col('pos') - 1 + pl.col('ref').str.len_chars()
    )
    .select(['id', 'Chromosome', 'Start', 'End', 'ref', 'alt', 'gene'])
)

anno_pr = pr.PyRanges(anno.to_pandas())

anno_pr

+------------------------+--------------+-----------+-----------+-------+
| id                     | Chromosome   | Start     | End       | +3    |
| (object)               | (category)   | (int64)   | (int64)   | ...   |
|------------------------+--------------+-----------+-----------+-------|
| chr1:214626910:A:G     | chr1         | 214626909 | 214626910 | ...   |
| chr1:21556831:T:G      | chr1         | 21556830  | 21556831  | ...   |
| chr1:21569280:C:A      | chr1         | 21569279  | 21569280  | ...   |
| chr1:21556795:T:C      | chr1         | 21556794  | 21556795  | ...   |
| ...                    | ...          | ...       | ...       | ...   |
| chr22:36919903:GCATA:G | chr22        | 36919902  | 36919907  | ...   |
| chr22:41102783:GT:G    | chr22        | 41102782  | 41102784  | ...   |
| chr22:24508167:ATC:A   | chr22        | 24508166  | 24508169  | ...   |
| chr22:41106250:GT:G    | chr22        | 41106249  | 41106251  | ...   |
+------------------------+--------------+-----------+-----------+-------+
Unstranded PyRanges object has 25,373,677 rows and 7 columns from 22 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
3 hidden columns: ref, alt, gene

In [14]:
anno_pr_nc = anno_pr.overlap(gencode_coding_regions, invert=True)
anno_pr_nc

+------------------------+--------------+-----------+-----------+-------+
| id                     | Chromosome   | Start     | End       | +3    |
| (object)               | (category)   | (int64)   | (int64)   | ...   |
|------------------------+--------------+-----------+-----------+-------|
| chr1:214626910:A:G     | chr1         | 214626909 | 214626910 | ...   |
| chr1:21556831:T:G      | chr1         | 21556830  | 21556831  | ...   |
| chr1:21569280:C:A      | chr1         | 21569279  | 21569280  | ...   |
| chr1:21556795:T:C      | chr1         | 21556794  | 21556795  | ...   |
| ...                    | ...          | ...       | ...       | ...   |
| chr22:36919903:GCATA:G | chr22        | 36919902  | 36919907  | ...   |
| chr22:41102783:GT:G    | chr22        | 41102782  | 41102784  | ...   |
| chr22:24508167:ATC:A   | chr22        | 24508166  | 24508169  | ...   |
| chr22:41106250:GT:G    | chr22        | 41106249  | 41106251  | ...   |
+------------------------+--------------+-----------+-----------+-------+
Unstranded PyRanges object has 23,367,788 rows and 7 columns from 22 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
3 hidden columns: ref, alt, gene

In [15]:
anno_pr_coding = anno_pr.overlap(gencode_coding_regions)
print('Coding variants:', len(anno_pr_coding))

anno_pr_coding
# anno_pr_coding.df['consequence'].value_counts()

Coding variants: 2005889

+--------------------------+--------------+-----------+-----------+-------+
| id                       | Chromosome   | Start     | End       | +3    |
| (object)                 | (category)   | (int64)   | (int64)   | ...   |
|--------------------------+--------------+-----------+-----------+-------|
| chr1:198320819:T:C       | chr1         | 198320818 | 198320819 | ...   |
| chr1:198320797:G:C       | chr1         | 198320796 | 198320797 | ...   |
| chr1:214646777:A:G       | chr1         | 214646776 | 214646777 | ...   |
| chr1:198256393:C:T       | chr1         | 198256392 | 198256393 | ...   |
| ...                      | ...          | ...       | ...       | ...   |
| chr22:28738166:CTG:C     | chr22        | 28738165  | 28738168  | ...   |
| chr22:40040232:CAG:C     | chr22        | 40040231  | 40040234  | ...   |
| chr22:36940069:GTA:G     | chr22        | 36940068  | 36940071  | ...   |
| chr22:17093668:AGGTAAC:A | chr22        | 17093667  | 17093674  | ...   |
+--------------------------+--------------+-----------+-----------+-------+
Unstranded PyRanges object has 2,005,889 rows and 7 columns from 22 chromosomes.
For printing, the PyRanges was sorted on Chromosome.
3 hidden columns: ref, alt, gene

In [16]:
set(anno_pr_nc.df['id'].to_list()).intersection(set(anno_pr_coding.df['id'].to_list()))

set()

## Merge back with annotations df

In [17]:
anno_pl_nc = pl.from_pandas(anno_pr_nc.df)

anno_pl_nc = anno_pl_nc.with_columns(
    gencode_non_coding = pl.lit(True),
    Chromosome = pl.col('Chromosome').cast(pl.Utf8)
)

anno_pl_nc

shape: (23_367_788, 8)
┌──────────────┬────────────┬───────────┬───────────┬────────────┬─────┬─────────────┬─────────────┐
│ id           ┆ Chromosome ┆ Start     ┆ End       ┆ ref        ┆ alt ┆ gene        ┆ gencode_non │
│ ---          ┆ ---        ┆ ---       ┆ ---       ┆ ---        ┆ --- ┆ ---         ┆ _coding     │
│ str          ┆ str        ┆ i64       ┆ i64       ┆ str        ┆ str ┆ str         ┆ ---         │
│              ┆            ┆           ┆           ┆            ┆     ┆             ┆ bool        │
╞══════════════╪════════════╪═══════════╪═══════════╪════════════╪═════╪═════════════╪═════════════╡
│ chr1:2146269 ┆ chr1       ┆ 214626909 ┆ 214626910 ┆ A          ┆ G   ┆ ENSG0000011 ┆ true        │
│ 10:A:G       ┆            ┆           ┆           ┆            ┆     ┆ 7724        ┆             │
│ chr1:2155683 ┆ chr1       ┆ 21556830  ┆ 21556831  ┆ T          ┆ G   ┆ ENSG0000016 ┆ true        │
│ 1:T:G        ┆            ┆           ┆           ┆            ┆     ┆ 2551        ┆             │
│ chr1:2156928 ┆ chr1       ┆ 21569279  ┆ 21569280  ┆ C          ┆ A   ┆ ENSG0000016 ┆ true        │
│ 0:C:A        ┆            ┆           ┆           ┆            ┆     ┆ 2551        ┆             │
│ chr1:2155679 ┆ chr1       ┆ 21556794  ┆ 21556795  ┆ T          ┆ C   ┆ ENSG0000016 ┆ true        │
│ 5:T:C        ┆            ┆           ┆           ┆            ┆     ┆ 2551        ┆             │
│ chr1:2146486 ┆ chr1       ┆ 214648629 ┆ 214648630 ┆ A          ┆ G   ┆ ENSG0000011 ┆ true        │
│ 30:A:G       ┆            ┆           ┆           ┆            ┆     ┆ 7724        ┆             │
│ …            ┆ …          ┆ …         ┆ …         ┆ …          ┆ …   ┆ …           ┆ …           │
│ chr22:411486 ┆ chr22      ┆ 41148659  ┆ 41148669  ┆ AATTTGTGTT ┆ A   ┆ ENSG0000010 ┆ true        │
│ 60:AATTTGTGT ┆            ┆           ┆           ┆            ┆     ┆ 0393        ┆             │
│ T:A          ┆            ┆           ┆           ┆            ┆     ┆             ┆             │
│ chr22:369199 ┆ chr22      ┆ 36919902  ┆ 36919907  ┆ GCATA      ┆ G   ┆ ENSG0000010 ┆ true        │
│ 03:GCATA:G   ┆            ┆           ┆           ┆            ┆     ┆ 0368        ┆             │
│ chr22:411027 ┆ chr22      ┆ 41102782  ┆ 41102784  ┆ GT         ┆ G   ┆ ENSG0000010 ┆ true        │
│ 83:GT:G      ┆            ┆           ┆           ┆            ┆     ┆ 0393        ┆             │
│ chr22:245081 ┆ chr22      ┆ 24508166  ┆ 24508169  ┆ ATC        ┆ A   ┆ ENSG0000010 ┆ true        │
│ 67:ATC:A     ┆            ┆           ┆           ┆            ┆     ┆ 0024        ┆             │
│ chr22:411062 ┆ chr22      ┆ 41106249  ┆ 41106251  ┆ GT         ┆ G   ┆ ENSG0000010 ┆ true        │
│ 50:GT:G      ┆            ┆           ┆           ┆            ┆     ┆ 0393        ┆             │
└──────────────┴────────────┴───────────┴───────────┴────────────┴─────┴─────────────┴─────────────┘

In [18]:
a = pl.scan_parquet('/s/project/deeprvat/wgs_preprocessing_rap/annotation/genebass394genes_olink371genes_variants_union_annotated_250928.parquet')
a.collect_schema().names()

['chrom',
 'pos',
 'ref',
 'alt',
 'id',
 'col',
 'gene',
 'distance',
 'polyphen',
 'cadd_raw',
 'am_pathogenicity',
 'spliceai_delta_score',
 'consequence_3_prime_utr_variant',
 'consequence_5_prime_utr_variant',
 'consequence_nmd_transcript_variant',
 'consequence_coding_sequence_variant',
 'consequence_downstream_gene_variant',
 'consequence_frameshift_variant',
 'consequence_inframe_deletion',
 'consequence_inframe_insertion',
 'consequence_intergenic_variant',
 'consequence_intron_variant',
 'consequence_missense_variant',
 'consequence_non_coding_transcript_exon_variant',
 'consequence_non_coding_transcript_variant',
 'consequence_protein_altering_variant',
 'consequence_splice_acceptor_variant',
 'consequence_splice_donor_5th_base_variant',
 'consequence_splice_donor_region_variant',
 'consequence_splice_donor_variant',
 'consequence_splice_polypyrimidine_tract_variant',
 'consequence_splice_region_variant',
 'consequence_start_lost',
 'consequence_start_retained_variant',
 'consequence_stop_gained',
 'consequence_stop_lost',
 'consequence_stop_retained_variant',
 'consequence_synonymous_variant',
 'consequence_upstream_gene_variant',
 'loftee_hc',
 'loftee_hc_is_nan',
 'loftee_lc',
 'loftee_lc_is_nan',
 'af_ukb',
 'afbeta_ukb',
 'afbeta_ukb_is_nan',
 'relative_cds_position',
 'next_in_frame_relative',
 'pangolin_score',
 'delta_score',
 'absplice_dna_max',
 'absplice2_max',
 'gpn_score',
 'five_prime_utr_variant_consequence_uaug_gained',
 'five_prime_utr_variant_consequence_uaug_lost',
 'five_prime_utr_variant_consequence_uframeshift',
 'five_prime_utr_variant_consequence_ustop_gained',
 'five_prime_utr_variant_consequence_ustop_lost',
 'variant_length',
 'promoterai',
 'gpn_score_is_nan',
 'promoterai_is_nan',
 'spliceai_delta_score_is_nan',
 'five_prime_utr_variant_consequence_ustop_lost_is_nan',
 'five_prime_utr_variant_consequence_uaug_lost_is_nan',
 'distance_is_nan',
 'am_pathogenicity_is_nan',
 'five_prime_utr_variant_consequence_ustop_gained_is_nan',
 'relative_cds_position_is_nan',
 'polyphen_is_nan',
 'absplice_dna_max_is_nan',
 'delta_score_is_nan',
 'five_prime_utr_variant_consequence_uaug_gained_is_nan',
 'next_in_frame_relative_is_nan',
 'absplice2_max_is_nan',
 'cadd_raw_is_nan',
 'five_prime_utr_variant_consequence_uframeshift_is_nan',
 'pangolin_score_is_nan',
 'region',
 'type',
 'length',
 'annotype',
 'consequence',
 'consscore',
 'consdetail',
 'gc',
 'cpg',
 'motifecount',
 'motifename',
 'motifehipos',
 'motifescorechng',
 'oaa',
 'naa',
 'featureid',
 'genename',
 'ccds',
 'intron',
 'exon',
 'cdnapos',
 'relcdnapos',
 'cdspos',
 'relcdspos',
 'protpos',
 'relprotpos',
 'domain',
 'dst2splice',
 'dst2spltype',
 'mindisttss',
 'mindisttse',
 'siftcat',
 'siftval',
 'polyphencat',
 'polyphenval',
 'priphcons',
 'mamphcons',
 'verphcons',
 'priphylop',
 'mamphylop',
 'verphylop',
 'bstatistic',
 'targetscan',
 'mirsvr-score',
 'mirsvr-e',
 'mirsvr-aln',
 'chmm_e1',
 'chmm_e2',
 'chmm_e3',
 'chmm_e4',
 'chmm_e5',
 'chmm_e6',
 'chmm_e7',
 'chmm_e8',
 'chmm_e9',
 'chmm_e10',
 'chmm_e11',
 'chmm_e12',
 'chmm_e13',
 'chmm_e14',
 'chmm_e15',
 'chmm_e16',
 'chmm_e17',
 'chmm_e18',
 'chmm_e19',
 'chmm_e20',
 'chmm_e21',
 'chmm_e22',
 'chmm_e23',
 'chmm_e24',
 'chmm_e25',
 'gerprs',
 'gerprspval',
 'gerpn',
 'gerps',
 'toverlapmotifs',
 'motifdist',
 'encodeh3k4me1-sum',
 'encodeh3k4me1-max',
 'encodeh3k4me2-sum',
 'encodeh3k4me2-max',
 'encodeh3k4me3-sum',
 'encodeh3k4me3-max',
 'encodeh3k9ac-sum',
 'encodeh3k9ac-max',
 'encodeh3k9me3-sum',
 'encodeh3k9me3-max',
 'encodeh3k27ac-sum',
 'encodeh3k27ac-max',
 'encodeh3k27me3-sum',
 'encodeh3k27me3-max',
 'encodeh3k36me3-sum',
 'encodeh3k36me3-max',
 'encodeh3k79me2-sum',
 'encodeh3k79me2-max',
 'encodeh4k20me1-sum',
 'encodeh4k20me1-max',
 'encodeh2afz-sum',
 'encodeh2afz-max',
 'encodednase-sum',
 'encodednase-max',
 'encodetotalrna-sum',
 'encodetotalrna-max',
 'grantham',
 'spliceai-acc-gain',
 'spliceai-acc-loss',
 'spliceai-don-gain',
 'spliceai-don-loss',
 'mmsp_acceptorintron',
 'mmsp_acceptor',
 'mmsp_exon',
 'mmsp_donor',
 'mmsp_donorintron',
 'dist2mutation',
 'freq100bp',
 'rare100bp',
 'sngl100bp',
 'freq1000bp',
 'rare1000bp',
 'sngl1000bp',
 'freq10000bp',
 'rare10000bp',
 'sngl10000bp',
 'ensembleregulatoryfeature',
 'dbscsnv-ada_score',
 'dbscsnv-rf_score',
 'remapoverlaptf',
 'remapoverlapcl',
 'esmscoremissense',
 'esmscoreinframe',
 'esmscoreframeshift',
 'regseq0',
 'regseq1',
 'regseq2',
 'regseq3',
 'regseq4',
 'regseq5',
 'regseq6',
 'regseq7',
 'aparent2',
 'zoopriphylop',
 'zooverphylop',
 'zoorocc',
 'zoouce',
 'roulette-filter',
 'roulette-mr',
 'roulette-ar',
 'cadd_rawscore',
 'cadd_phred',
 'type_is_nan',
 'length_is_nan',
 'annotype_is_nan',
 'consequence_is_nan',
 'consscore_is_nan',
 'consdetail_is_nan',
 'gc_is_nan',
 'cpg_is_nan',
 'motifecount_is_nan',
 'motifename_is_nan',
 'motifehipos_is_nan',
 'motifescorechng_is_nan',
 'oaa_is_nan',
 'naa_is_nan',
 'featureid_is_nan',
 'genename_is_nan',
 'ccds_is_nan',
 'intron_is_nan',
 'exon_is_nan',
 'cdnapos_is_nan',
 'relcdnapos_is_nan',
 'cdspos_is_nan',
 'relcdspos_is_nan',
 'protpos_is_nan',
 'relprotpos_is_nan',
 'domain_is_nan',
 'dst2splice_is_nan',
 'dst2spltype_is_nan',
 'mindisttss_is_nan',
 'mindisttse_is_nan',
 'siftcat_is_nan',
 'siftval_is_nan',
 'polyphencat_is_nan',
 'polyphenval_is_nan',
 'priphcons_is_nan',
 'mamphcons_is_nan',
 'verphcons_is_nan',
 'priphylop_is_nan',
 'mamphylop_is_nan',
 'verphylop_is_nan',
 'bstatistic_is_nan',
 'targetscan_is_nan',
 'mirsvr-score_is_nan',
 'mirsvr-e_is_nan',
 'mirsvr-aln_is_nan',
 'chmm_e1_is_nan',
 'chmm_e2_is_nan',
 'chmm_e3_is_nan',
 'chmm_e4_is_nan',
 'chmm_e5_is_nan',
 'chmm_e6_is_nan',
 'chmm_e7_is_nan',
 'chmm_e8_is_nan',
 'chmm_e9_is_nan',
 'chmm_e10_is_nan',
 'chmm_e11_is_nan',
 'chmm_e12_is_nan',
 'chmm_e13_is_nan',
 'chmm_e14_is_nan',
 'chmm_e15_is_nan',
 'chmm_e16_is_nan',
 'chmm_e17_is_nan',
 'chmm_e18_is_nan',
 'chmm_e19_is_nan',
 'chmm_e20_is_nan',
 'chmm_e21_is_nan',
 'chmm_e22_is_nan',
 'chmm_e23_is_nan',
 'chmm_e24_is_nan',
 'chmm_e25_is_nan',
 'gerprs_is_nan',
 'gerprspval_is_nan',
 'gerpn_is_nan',
 'gerps_is_nan',
 'toverlapmotifs_is_nan',
 'motifdist_is_nan',
 'encodeh3k4me1-sum_is_nan',
 'encodeh3k4me1-max_is_nan',
 'encodeh3k4me2-sum_is_nan',
 'encodeh3k4me2-max_is_nan',
 'encodeh3k4me3-sum_is_nan',
 'encodeh3k4me3-max_is_nan',
 'encodeh3k9ac-sum_is_nan',
 'encodeh3k9ac-max_is_nan',
 'encodeh3k9me3-sum_is_nan',
 'encodeh3k9me3-max_is_nan',
 'encodeh3k27ac-sum_is_nan',
 'encodeh3k27ac-max_is_nan',
 'encodeh3k27me3-sum_is_nan',
 'encodeh3k27me3-max_is_nan',
 'encodeh3k36me3-sum_is_nan',
 'encodeh3k36me3-max_is_nan',
 'encodeh3k79me2-sum_is_nan',
 'encodeh3k79me2-max_is_nan',
 'encodeh4k20me1-sum_is_nan',
 'encodeh4k20me1-max_is_nan',
 'encodeh2afz-sum_is_nan',
 'encodeh2afz-max_is_nan',
 'encodednase-sum_is_nan',
 'encodednase-max_is_nan',
 'encodetotalrna-sum_is_nan',
 'encodetotalrna-max_is_nan',
 'grantham_is_nan',
 'spliceai-acc-gain_is_nan',
 'spliceai-acc-loss_is_nan',
 'spliceai-don-gain_is_nan',
 'spliceai-don-loss_is_nan',
 'mmsp_acceptorintron_is_nan',
 'mmsp_acceptor_is_nan',
 'mmsp_exon_is_nan',
 'mmsp_donor_is_nan',
 'mmsp_donorintron_is_nan',
 'dist2mutation_is_nan',
 'freq100bp_is_nan',
 'rare100bp_is_nan',
 'sngl100bp_is_nan',
 'freq1000bp_is_nan',
 'rare1000bp_is_nan',
 'sngl1000bp_is_nan',
 'freq10000bp_is_nan',
 'rare10000bp_is_nan',
 'sngl10000bp_is_nan',
 'ensembleregulatoryfeature_is_nan',
 'dbscsnv-ada_score_is_nan',
 'dbscsnv-rf_score_is_nan',
 'remapoverlaptf_is_nan',
 'remapoverlapcl_is_nan',
 'esmscoremissense_is_nan',
 'esmscoreinframe_is_nan',
 'esmscoreframeshift_is_nan',
 'regseq0_is_nan',
 'regseq1_is_nan',
 'regseq2_is_nan',
 'regseq3_is_nan',
 'regseq4_is_nan',
 'regseq5_is_nan',
 'regseq6_is_nan',
 'regseq7_is_nan',
 'aparent2_is_nan',
 'zoopriphylop_is_nan',
 'zooverphylop_is_nan',
 'zoorocc_is_nan',
 'zoouce_is_nan',
 'roulette-filter_is_nan',
 'roulette-mr_is_nan',
 'roulette-ar_is_nan',
 'cadd_rawscore_is_nan',
 'cadd_phred_is_nan',
 'TSS',
 'Strand',
 'gene_length',
 'gene_name',
 'dist_to_tss',
 'abexp_max',
 'abexp_min',
 'promoterai_abs',
 'promoterai_over',
 'promoterai_under',
 'gpn_star_llr_calibrated_mean']

In [19]:
vep_coding = [
    'consequence_coding_sequence_variant',
    'consequence_nmd_transcript_variant',
    'consequence_frameshift_variant',
    'consequence_missense_variant',
    'consequence_protein_altering_variant',
    'consequence_splice_acceptor_variant',
    'consequence_splice_donor_5th_base_variant',
    'consequence_splice_donor_region_variant',
    'consequence_splice_donor_variant',
    'consequence_splice_polypyrimidine_tract_variant',
    'consequence_splice_region_variant',
    'consequence_start_lost',
    'consequence_start_retained_variant',
    'consequence_stop_gained',
    'consequence_stop_lost',
    'consequence_stop_retained_variant',
    'consequence_synonymous_variant',
]

vep_nc = [
    'consequence_3_prime_utr_variant',
    'consequence_5_prime_utr_variant',
    'consequence_downstream_gene_variant',
    'consequence_inframe_deletion',
    'consequence_inframe_insertion',
    'consequence_intergenic_variant',
    'consequence_intron_variant',
    'consequence_non_coding_transcript_exon_variant',
    'consequence_non_coding_transcript_variant',
    'consequence_upstream_gene_variant'
]

In [ ]:
anno = (
    pl.scan_parquet(
        '/s/project/deeprvat/wgs_preprocessing_rap/annotation/genebass394genes_olink371genes_variants_union_annotated_250928.parquet',
    )
    .with_columns(
        vep_coding = pl.sum_horizontal(vep_coding) > 0,
    )
    .collect()
)

anno

shape: (25_373_677, 387)
┌───────┬───────────┬─────────────┬─────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ chrom ┆ pos       ┆ ref         ┆ alt ┆ … ┆ promoterai_ ┆ promoterai_ ┆ gpn_star_ll ┆ vep_coding │
│ ---   ┆ ---       ┆ ---         ┆ --- ┆   ┆ over        ┆ under       ┆ r_calibrate ┆ ---        │
│ str   ┆ i32       ┆ str         ┆ str ┆   ┆ ---         ┆ ---         ┆ d_mean      ┆ bool       │
│       ┆           ┆             ┆     ┆   ┆ f32         ┆ f32         ┆ ---         ┆            │
│       ┆           ┆             ┆     ┆   ┆             ┆             ┆ f64         ┆            │
╞═══════╪═══════════╪═════════════╪═════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ chr2  ┆ 169197167 ┆ T           ┆ G   ┆ … ┆ 0.0         ┆ 0.0         ┆ 0.153293    ┆ false      │
│ chr2  ┆ 169204292 ┆ A           ┆ T   ┆ … ┆ 0.0         ┆ 0.0         ┆ 1.684965    ┆ false      │
│ chr2  ┆ 169030531 ┆ C           ┆ T   ┆ … ┆ 0.0         ┆ 0.0         ┆ -1.212965   ┆ false      │
│ chr2  ┆ 168910825 ┆ T           ┆ G   ┆ … ┆ 0.0         ┆ 0.0         ┆ -1.479978   ┆ false      │
│ chr2  ┆ 168969544 ┆ T           ┆ C   ┆ … ┆ 0.0         ┆ 0.0         ┆ -2.904763   ┆ true       │
│ …     ┆ …         ┆ …           ┆ …   ┆ … ┆ …           ┆ …           ┆ …           ┆ …          │
│ chr15 ┆ 34974609  ┆ ACTTCT      ┆ A   ┆ … ┆ 0.0         ┆ 0.0         ┆ null        ┆ false      │
│ chr9  ┆ 132358570 ┆ C           ┆ A   ┆ … ┆ 0.0         ┆ 0.0         ┆ -1.033277   ┆ false      │
│ chr8  ┆ 13200986  ┆ C           ┆ CA  ┆ … ┆ 0.0         ┆ 0.0         ┆ null        ┆ false      │
│ chr12 ┆ 122065447 ┆ G           ┆ A   ┆ … ┆ 0.0         ┆ 0.0         ┆ -2.975401   ┆ false      │
│ chr5  ┆ 180321761 ┆ GGTTTTGTTTT ┆ G   ┆ … ┆ 0.0         ┆ 0.0         ┆ null        ┆ false      │
│       ┆           ┆ GTTTTGTTTTG ┆     ┆   ┆             ┆             ┆             ┆            │
│       ┆           ┆ TTTT        ┆     ┆   ┆             ┆             ┆             ┆            │
└───────┴───────────┴─────────────┴─────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [21]:
anno_pl = anno.join(anno_pl_nc[['id', 'gene', 'gencode_non_coding']], on=['id', 'gene'], how='left').with_columns(pl.col("gencode_non_coding").fill_null(False))

anno_pl = anno_pl.with_columns(
    vep_gencode_non_coding = (pl.col('vep_coding')==False) & (pl.col('gencode_non_coding')==True)
)

anno_pl

shape: (25_373_677, 389)
┌───────┬───────────┬─────────────┬─────┬───┬─────────────┬────────────┬─────────────┬─────────────┐
│ chrom ┆ pos       ┆ ref         ┆ alt ┆ … ┆ gpn_star_ll ┆ vep_coding ┆ gencode_non ┆ vep_gencode │
│ ---   ┆ ---       ┆ ---         ┆ --- ┆   ┆ r_calibrate ┆ ---        ┆ _coding     ┆ _non_coding │
│ str   ┆ i32       ┆ str         ┆ str ┆   ┆ d_mean      ┆ bool       ┆ ---         ┆ ---         │
│       ┆           ┆             ┆     ┆   ┆ ---         ┆            ┆ bool        ┆ bool        │
│       ┆           ┆             ┆     ┆   ┆ f64         ┆            ┆             ┆             │
╞═══════╪═══════════╪═════════════╪═════╪═══╪═════════════╪════════════╪═════════════╪═════════════╡
│ chr2  ┆ 169197167 ┆ T           ┆ G   ┆ … ┆ 0.153293    ┆ false      ┆ true        ┆ true        │
│ chr2  ┆ 169204292 ┆ A           ┆ T   ┆ … ┆ 1.684965    ┆ false      ┆ true        ┆ true        │
│ chr2  ┆ 169030531 ┆ C           ┆ T   ┆ … ┆ -1.212965   ┆ false      ┆ true        ┆ true        │
│ chr2  ┆ 168910825 ┆ T           ┆ G   ┆ … ┆ -1.479978   ┆ false      ┆ true        ┆ true        │
│ chr2  ┆ 168969544 ┆ T           ┆ C   ┆ … ┆ -2.904763   ┆ true       ┆ false       ┆ false       │
│ …     ┆ …         ┆ …           ┆ …   ┆ … ┆ …           ┆ …          ┆ …           ┆ …           │
│ chr15 ┆ 34974609  ┆ ACTTCT      ┆ A   ┆ … ┆ null        ┆ false      ┆ true        ┆ true        │
│ chr9  ┆ 132358570 ┆ C           ┆ A   ┆ … ┆ -1.033277   ┆ false      ┆ true        ┆ true        │
│ chr8  ┆ 13200986  ┆ C           ┆ CA  ┆ … ┆ null        ┆ false      ┆ true        ┆ true        │
│ chr12 ┆ 122065447 ┆ G           ┆ A   ┆ … ┆ -2.975401   ┆ false      ┆ true        ┆ true        │
│ chr5  ┆ 180321761 ┆ GGTTTTGTTTT ┆ G   ┆ … ┆ null        ┆ false      ┆ true        ┆ true        │
│       ┆           ┆ GTTTTGTTTTG ┆     ┆   ┆             ┆            ┆             ┆             │
│       ┆           ┆ TTTT        ┆     ┆   ┆             ┆            ┆             ┆             │
└───────┴───────────┴─────────────┴─────┴───┴─────────────┴────────────┴─────────────┴─────────────┘

In [ ]:
# anno_pl.write_parquet('/s/project/deeprvat/wgs_preprocessing_rap/annotation/genebass394genes_olink371genes_variants_union_annotated_genocode_251031.parquet')

In [23]:
anno_pl.filter(
    (pl.col('gencode_non_coding') == True) &
    (pl.col('vep_gencode_non_coding') == False)
)

shape: (152_109, 389)
┌───────┬───────────┬─────────────┬─────┬───┬─────────────┬────────────┬─────────────┬─────────────┐
│ chrom ┆ pos       ┆ ref         ┆ alt ┆ … ┆ gpn_star_ll ┆ vep_coding ┆ gencode_non ┆ vep_gencode │
│ ---   ┆ ---       ┆ ---         ┆ --- ┆   ┆ r_calibrate ┆ ---        ┆ _coding     ┆ _non_coding │
│ str   ┆ i32       ┆ str         ┆ str ┆   ┆ d_mean      ┆ bool       ┆ ---         ┆ ---         │
│       ┆           ┆             ┆     ┆   ┆ ---         ┆            ┆ bool        ┆ bool        │
│       ┆           ┆             ┆     ┆   ┆ f64         ┆            ┆             ┆             │
╞═══════╪═══════════╪═════════════╪═════╪═══╪═════════════╪════════════╪═════════════╪═════════════╡
│ chr2  ┆ 169220575 ┆ A           ┆ G   ┆ … ┆ -3.372177   ┆ true       ┆ true        ┆ false       │
│ chr2  ┆ 165365131 ┆ A           ┆ G   ┆ … ┆ -2.254203   ┆ true       ┆ true        ┆ false       │
│ chr2  ┆ 168958139 ┆ G           ┆ C   ┆ … ┆ -1.00055    ┆ true       ┆ true        ┆ false       │
│ chr2  ┆ 169013520 ┆ C           ┆ T   ┆ … ┆ -3.162808   ┆ true       ┆ true        ┆ false       │
│ chr2  ┆ 168964311 ┆ G           ┆ C   ┆ … ┆ -10.263983  ┆ true       ┆ true        ┆ false       │
│ …     ┆ …         ┆ …           ┆ …   ┆ … ┆ …           ┆ …          ┆ …           ┆ …           │
│ chr6  ┆ 16285842  ┆ CCGGGCCCTGG ┆ C   ┆ … ┆ null        ┆ true       ┆ true        ┆ false       │
│       ┆           ┆ TG          ┆     ┆   ┆             ┆            ┆             ┆             │
│ chr19 ┆ 38593223  ┆ GCT         ┆ G   ┆ … ┆ null        ┆ true       ┆ true        ┆ false       │
│ chr7  ┆ 117548621 ┆ TGTGTGTG    ┆ T   ┆ … ┆ null        ┆ true       ┆ true        ┆ false       │
│ chr3  ┆ 188630924 ┆ GA          ┆ G   ┆ … ┆ null        ┆ true       ┆ true        ┆ false       │
│ chr2  ┆ 27232441  ┆ A           ┆ AT  ┆ … ┆ null        ┆ true       ┆ true        ┆ false       │
└───────┴───────────┴─────────────┴─────┴───┴─────────────┴────────────┴─────────────┴─────────────┘