In [7]:
import yaml
import numpy as np
import polars as pl

patho_labels  = ['Pathogenic', 'Likely_pathogenic']
benign_labels = ['Benign', 'Likely_benign']

clinvar_labels = patho_labels + benign_labels

# Create input for VEP and annotation pipeline

In [ ]:
# CLINVAR_URL = "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar_20260621.vcf.gz"

# !wget -P /s/project/ukbbgym/annotation_files/clinvar/ {CLINVAR_URL}

In [ ]:
annotation_dir = "/s/project/ukbbgym/annotation_files/clinvar"
clinvar_vcf_path = "/s/project/ukbbgym/annotation_files/clinvar/clinvar_20260621.vcf.gz"

clinvar = (
    pl.scan_csv(
        clinvar_vcf_path,
        separator="\t",
        comment_prefix="##",
        schema_overrides={"#CHROM": pl.Utf8, "POS": pl.Int64},
        ignore_errors=True,
    )
    .rename({"#CHROM": "chrom", "POS": "pos", "REF": "ref", "ALT": "alt"})
    .with_columns(
        chrom="chr" + pl.col("chrom").cast(pl.Utf8).str.replace(r"^chr", ""),
        clinical_significance=pl.col("INFO").str.extract(r"CLNSIG=([^;]+)", 1),
    )
    .with_columns(
        id=pl.concat_str(["chrom", "pos", "ref", "alt"], separator=":"),
    )
    .select(["id", "chrom", "pos", "ref", "alt", "clinical_significance"])
    .filter(pl.col("clinical_significance").is_in(clinvar_labels))
    .unique(subset="id")          # one row per variant
    .collect()
)

# 1. variant_metadata.parquet — exactly the schema the Snakefile consumes
clinvar.select("id", "chrom", "pos", "ref", "alt").write_parquet(
    f"{annotation_dir}/variant_metadata.parquet"
)

# 2. keep the labels to join back onto the final annotation output on `id`
clinvar.select("id", "clinical_significance").write_parquet(
    f"{annotation_dir}/clinvar_labels.parquet"
)

# Add more missense annotations

In [8]:
import add_more_annotations as ann

In [9]:
cv_all = (
    pl.read_parquet("/s/project/ukbbgym/annotation_files/clinvar/vep_annotations_processed_cadd_fill_na.parquet")
)

cv_all

shape: (1_859_698, 184)
┌────────────┬───────┬───────────┬─────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id         ┆ chrom ┆ pos       ┆ ref     ┆ … ┆ verphcons_ ┆ verphylop_ ┆ cpt1_llr_i ┆ blosum62_i │
│ ---        ┆ ---   ┆ ---       ┆ ---     ┆   ┆ is_na      ┆ is_na      ┆ s_na       ┆ s_na       │
│ str        ┆ str   ┆ i64       ┆ str     ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│            ┆       ┆           ┆         ┆   ┆ i8         ┆ i8         ┆ i8         ┆ i8         │
╞════════════╪═══════╪═══════════╪═════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr4:10268 ┆ chr4  ┆ 102689649 ┆ A       ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 1          │
│ 9649:A:G   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr4:10268 ┆ chr4  ┆ 102689661 ┆ C       ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 1          │
│ 9661:C:T   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr4:10269 ┆ chr4  ┆ 102690583 ┆ T       ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 1          │
│ 0583:T:G   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr4:10269 ┆ chr4  ┆ 102690671 ┆ C       ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 1          │
│ 0671:C:T   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr4:10269 ┆ chr4  ┆ 102690674 ┆ C       ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 1          │
│ 0674:C:T   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ …          ┆ …     ┆ …         ┆ …       ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ chr5:14064 ┆ chr5  ┆ 140647688 ┆ GC      ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 1          │
│ 7688:GC:G  ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr2:43912 ┆ chr2  ┆ 43912558  ┆ CCT     ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 1          │
│ 558:CCT:C  ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr11:1256 ┆ chr11 ┆ 125602442 ┆ G       ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 1          │
│ 02442:G:GT ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr10:5382 ┆ chr10 ┆ 53822445  ┆ CAGGAGG ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 1          │
│ 2445:CAGGA ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ GG:C       ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr17:7673 ┆ chr17 ┆ 7673346   ┆ AAT     ┆ … ┆ 1          ┆ 1          ┆ 1          ┆ 1          │
│ 346:AAT:A  ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
└────────────┴───────┴───────────┴─────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [10]:
ann.main(
    "/s/project/ukbbgym/annotation_files/clinvar/vep_annotations_processed_cadd_fill_na.parquet",
    fill_null_defaults_path="fill_null_defaults.yaml",
    output_path="/s/project/ukbbgym/annotation_files/clinvar/vep_annotations_processed_cadd_fill_na_more.parquet",
    download_dir="/s/project/ukbbgym/annotation_files/more_annotations",
    add_alphamissense=False,
    add_cpt1=False,
    add_cadd=False,
    add_gpn_msa=False,
    add_phylop=False,
    add_next_in_frame=False,
)

[2026-06-24 21:06:57,271] INFO:add_more_annotations: === Downloading required files ===
[2026-06-24 21:06:57,274] INFO:add_more_annotations:   Already complete: /s/project/ukbbgym/annotation_files/more_annotations/tmp/clinvar.vcf.gz
[2026-06-24 21:06:57,275] INFO:add_more_annotations: === Auto-downloading annotation scores ===
[2026-06-24 21:06:57,281] INFO:add_more_annotations:   Already complete: /s/project/ukbbgym/annotation_files/more_annotations/tmp/revel.zip
[2026-06-24 21:06:57,288] INFO:add_more_annotations:   Already extracted: /s/project/ukbbgym/annotation_files/more_annotations/tmp/revel.zip -> /s/project/ukbbgym/annotation_files/more_annotations/tmp/revel
[2026-06-24 21:06:57,291] INFO:add_more_annotations:   Already present: /s/project/ukbbgym/annotation_files/more_annotations/tmp/ClinPred_hg38.txt.gz
[2026-06-24 21:06:57,292] INFO:add_more_annotations:   Already present: /s/project/ukbbgym/annotation_files/more_annotations/tmp/bayesdel.gz
[2026-06-24 21:06:57,296] INFO:add_more_annotations:   Already complete: /s/project/ukbbgym/annotation_files/more_annotations/tmp/grch38_popEVE.vcf.gz
[2026-06-24 21:06:57,296] INFO:add_more_annotations: === Building UniProt map ===
[2026-06-24 21:06:57,299] INFO:add_more_annotations:   Already complete: /s/project/ukbbgym/annotation_files/more_annotations/tmp/HUMAN_9606_idmapping.dat.gz
[2026-06-24 21:06:57,847] INFO:add_more_annotations: === Loading VEP parquet ===
[2026-06-24 21:06:57,850] INFO:add_more_annotations: === Harmonizing AoU schema ===
[2026-06-24 21:06:57,876] INFO:add_more_annotations: Loaded 1,859,698 rows
[2026-06-24 21:06:57,877] INFO:add_more_annotations: === Group 0: VEP / LOFTEE post-processing ===
[2026-06-24 21:06:57,877] INFO:add_more_annotations: Step 0a: LOFTEE dummies + consequence one-hot
[2026-06-24 21:06:57,877] WARNING:add_more_annotations:   'lof' column absent; skipping LOFTEE dummies
[2026-06-24 21:06:57,878] WARNING:add_more_annotations:   No consequence column found; skipping one-hot
[2026-06-24 21:06:57,878] INFO:add_more_annotations: Step 0b: VEP structural features
[2026-06-24 21:06:59,027] INFO:add_more_annotations:   dist_to_tss / gene_length / gene_name OK
[2026-06-24 21:06:59,028] WARNING:add_more_annotations:   cds_start absent; skipping relative_cds_position. Extract from vep.transcript_consequences[].cds_start in Hail.
[2026-06-24 21:06:59,034] INFO:add_more_annotations: === Group 1: Missense predictors ===
[2026-06-24 21:06:59,035] INFO:add_more_annotations: Step 1b: Merging REVEL scores
[2026-06-24 21:06:59,874] INFO:add_more_annotations:   ENST→ENSG map (Gencode): 246,452 entries
[2026-06-24 21:08:15,051] INFO:add_more_annotations:   REVEL OK
[2026-06-24 21:08:15,052] INFO:add_more_annotations: Step 1c: Merging ClinPred scores
[2026-06-24 21:08:15,104] INFO:add_more_annotations:   ClinPred OK
[2026-06-24 21:08:15,104] INFO:add_more_annotations: Step 1d: Merging BayesDel scores
[2026-06-24 21:08:19,469] INFO:add_more_annotations:   BayesDel OK
[2026-06-24 21:08:19,470] INFO:add_more_annotations: Step 1e: Merging popEVE scores
[2026-06-24 21:08:45,888] INFO:add_more_annotations:   popEVE OK
[2026-06-24 21:08:45,889] INFO:add_more_annotations: === Group 2: CADD / conservation ===
[2026-06-24 21:08:45,889] INFO:add_more_annotations: === Group 3: Derived columns + fill nulls ===
[2026-06-24 21:08:45,889] INFO:add_more_annotations: Step 3a: Adding derived columns
[2026-06-24 21:08:45,891] INFO:add_more_annotations: Step 3b: Filling nulls and adding _is_na indicators
[2026-06-24 21:08:45,894] INFO:add_more_annotations: === Group 4: Post-fill annotations ===
[2026-06-24 21:08:45,895] INFO:add_more_annotations: Step 4a: Adding AlphaFold pLDDT scores
[2026-06-24 21:09:18,130] INFO:add_more_annotations:   Need pLDDT for 17,620 proteins
[2026-06-24 21:10:36,638] INFO:add_more_annotations:   Extracted pLDDT for 17,464 proteins, 13,958,729 residues
[2026-06-24 21:10:37,004] INFO:add_more_annotations:   pLDDT OK
[2026-06-24 21:10:37,464] INFO:add_more_annotations: Step 4b: Adding PIONEER interface residues
[2026-06-24 21:10:37,473] INFO:add_more_annotations:   Already complete: /s/project/ukbbgym/annotation_files/more_annotations/tmp/pioneer_high_human.txt
[2026-06-24 21:11:13,551] INFO:add_more_annotations:   PIONEER interface residues: 612,643 pairs across 11,029 genes
[2026-06-24 21:11:13,552] INFO:add_more_annotations:   PIONEER OK
[2026-06-24 21:11:13,611] INFO:add_more_annotations: Step 4d: Merging ClinVar annotations
[2026-06-24 21:11:58,615] INFO:add_more_annotations:   ClinVar OK
[2026-06-24 21:11:58,616] INFO:add_more_annotations: === Collecting and writing output parquet ===
[2026-06-24 21:12:43,924] INFO:add_more_annotations: Output written to /s/project/ukbbgym/annotation_files/clinvar/vep_annotations_processed_cadd_fill_na_more.parquet
[2026-06-24 21:12:45,002] INFO:add_more_annotations: Removed scratch download dir /s/project/ukbbgym/annotation_files/more_annotations/tmp

'/s/project/ukbbgym/annotation_files/clinvar/vep_annotations_processed_cadd_fill_na_more.parquet'

# Add clinical significance labels to the final annotation output

In [11]:
cv_all = (
    pl.read_parquet("/s/project/ukbbgym/annotation_files/clinvar/vep_annotations_processed_cadd_fill_na_more.parquet")
)

cv_all

shape: (1_859_698, 230)
┌────────────┬───────┬───────────┬─────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id         ┆ chrom ┆ pos       ┆ ref     ┆ … ┆ clinvar_pa ┆ clinvar_li ┆ clinvar_be ┆ clinvar_li │
│ ---        ┆ ---   ┆ ---       ┆ ---     ┆   ┆ tho        ┆ kely_patho ┆ nign       ┆ kely_benig │
│ str        ┆ str   ┆ i64       ┆ str     ┆   ┆ ---        ┆ ---        ┆ ---        ┆ n          │
│            ┆       ┆           ┆         ┆   ┆ i8         ┆ i8         ┆ i8         ┆ ---        │
│            ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆ i8         │
╞════════════╪═══════╪═══════════╪═════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr4:10268 ┆ chr4  ┆ 102689649 ┆ A       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ 9649:A:G   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr4:10268 ┆ chr4  ┆ 102689661 ┆ C       ┆ … ┆ 1          ┆ 0          ┆ 0          ┆ 0          │
│ 9661:C:T   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr4:10269 ┆ chr4  ┆ 102690583 ┆ T       ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 0          │
│ 0583:T:G   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr4:10269 ┆ chr4  ┆ 102690671 ┆ C       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ 0671:C:T   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr4:10269 ┆ chr4  ┆ 102690674 ┆ C       ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ 0674:C:T   ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ …          ┆ …     ┆ …         ┆ …       ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ chr5:14064 ┆ chr5  ┆ 140647688 ┆ GC      ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ 7688:GC:G  ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr2:43912 ┆ chr2  ┆ 43912558  ┆ CCT     ┆ … ┆ 0          ┆ 1          ┆ 0          ┆ 0          │
│ 558:CCT:C  ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr11:1256 ┆ chr11 ┆ 125602442 ┆ G       ┆ … ┆ 0          ┆ 0          ┆ 1          ┆ 0          │
│ 02442:G:GT ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr10:5382 ┆ chr10 ┆ 53822445  ┆ CAGGAGG ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ 2445:CAGGA ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ GG:C       ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
│ chr17:7673 ┆ chr17 ┆ 7673346   ┆ AAT     ┆ … ┆ 0          ┆ 0          ┆ 0          ┆ 1          │
│ 346:AAT:A  ┆       ┆           ┆         ┆   ┆            ┆            ┆            ┆            │
└────────────┴───────┴───────────┴─────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [12]:
cv_all.columns

['id',
 'chrom',
 'pos',
 'ref',
 'alt',
 'region',
 'cds_position',
 'protein_position',
 'distance',
 'amino_acids',
 'gnomade_af',
 'gnomadg_af',
 'polyphen',
 'sift',
 'cadd_phred',
 'cadd_raw',
 'am_pathogenicity',
 'loftee_hc',
 'loftee_lc',
 'relative_cds_position',
 'next_in_frame_relative',
 'spliceai_delta_score',
 'pangolin_score',
 'delta_score',
 'absplice_dna_max',
 'absplice2_max',
 'five_prime_utr_variant_consequence_uaug_gained',
 'five_prime_utr_variant_consequence_uaug_lost',
 'five_prime_utr_variant_consequence_uframeshift',
 'five_prime_utr_variant_consequence_ustop_gained',
 'five_prime_utr_variant_consequence_ustop_lost',
 'variant_length',
 'gpn_score',
 'promoterai',
 'score_pai3d',
 'blosum62',
 'is_indel',
 'is_insertion',
 'is_deletion',
 'mobi_full_disorder_priority',
 'mobi_curated_disorder_priority',
 'mobi_full_lip_priority',
 'ted_domain',
 'low_complexity_domain',
 'cpt1_llr',
 'encode_pls',
 'encode_pels',
 'encode_dels',
 'encode_ca',
 'encode_ca-ctcf',
 'encode_ca-tf',
 'encode_ca-h3k4me3',
 'encode_tf',
 'not_annotated_in_encode',
 'dist_to_tss',
 'aparent2',
 'cdspos',
 'cpg',
 'dst2splice',
 'esmscoreframeshift',
 'esmscoreinframe',
 'esmscoremissense',
 'gc',
 'gerpn',
 'gerps',
 'grantham',
 'remapoverlapcl',
 'remapoverlaptf',
 'roulette-ar',
 'roulette-mr',
 'zoopriphylop',
 'zoouce',
 'zooverphylop',
 'bstatistic',
 'cdnapos',
 'dbscsnv-ada_score',
 'dbscsnv-rf_score',
 'mamphcons',
 'mamphylop',
 'mindisttse',
 'mindisttss',
 'mirsvr-aln',
 'mirsvr-e',
 'mirsvr-score',
 'motifdist',
 'motifecount',
 'motifehipos',
 'motifescorechng',
 'priphcons',
 'priphylop',
 'relcdspos',
 'relprotpos',
 'relcdnapos',
 'toverlapmotifs',
 'targetscan',
 'verphcons',
 'verphylop',
 'consequence_3_prime_utr_variant',
 'consequence_5_prime_utr_variant',
 'consequence_coding_sequence_variant',
 'consequence_downstream_gene_variant',
 'consequence_frameshift_variant',
 'consequence_inframe_deletion',
 'consequence_inframe_insertion',
 'consequence_intron_variant',
 'consequence_missense_variant',
 'consequence_protein_altering_variant',
 'consequence_splice_acceptor_variant',
 'consequence_splice_donor_5th_base_variant',
 'consequence_splice_donor_region_variant',
 'consequence_splice_donor_variant',
 'consequence_splice_polypyrimidine_tract_variant',
 'consequence_splice_region_variant',
 'consequence_start_lost',
 'consequence_start_retained_variant',
 'consequence_stop_gained',
 'consequence_stop_lost',
 'consequence_stop_retained_variant',
 'consequence_synonymous_variant',
 'consequence_transcript_ablation',
 'consequence_upstream_gene_variant',
 'polyphen_is_na',
 'sift_is_na',
 'cadd_phred_is_na',
 'cadd_raw_is_na',
 'am_pathogenicity_is_na',
 'relative_cds_position_is_na',
 'next_in_frame_relative_is_na',
 'spliceai_delta_score_is_na',
 'pangolin_score_is_na',
 'delta_score_is_na',
 'absplice_dna_max_is_na',
 'absplice2_max_is_na',
 'variant_length_is_na',
 'gpn_score_is_na',
 'promoterai_is_na',
 'score_pai3d_is_na',
 'gene_length_is_na',
 'dist_to_tss_is_na',
 'aparent2_is_na',
 'cdspos_is_na',
 'cpg_is_na',
 'dst2splice_is_na',
 'esmscoreframeshift_is_na',
 'esmscoreinframe_is_na',
 'esmscoremissense_is_na',
 'gc_is_na',
 'gerpn_is_na',
 'gerps_is_na',
 'grantham_is_na',
 'remapoverlapcl_is_na',
 'remapoverlaptf_is_na',
 'roulette-ar_is_na',
 'roulette-mr_is_na',
 'zoopriphylop_is_na',
 'zoouce_is_na',
 'zooverphylop_is_na',
 'bstatistic_is_na',
 'cdnapos_is_na',
 'dbscsnv-ada_score_is_na',
 'dbscsnv-rf_score_is_na',
 'mamphcons_is_na',
 'mamphylop_is_na',
 'mindisttse_is_na',
 'mindisttss_is_na',
 'mirsvr-aln_is_na',
 'mirsvr-e_is_na',
 'mirsvr-score_is_na',
 'motifdist_is_na',
 'motifecount_is_na',
 'motifehipos_is_na',
 'motifescorechng_is_na',
 'priphcons_is_na',
 'priphylop_is_na',
 'relcdspos_is_na',
 'relprotpos_is_na',
 'relcdnapos_is_na',
 'toverlapmotifs_is_na',
 'targetscan_is_na',
 'verphcons_is_na',
 'verphylop_is_na',
 'cpt1_llr_is_na',
 'blosum62_is_na',
 'gene_name',
 'gene_length',
 'revel_score',
 'clinpred_score',
 'bayes_del',
 'popeve',
 'eve',
 'esm1v',
 'pop_adjusted_eve',
 'pop_adjusted_esm1v',
 'core_promoter',
 'proximal_promoter',
 'encode_enhancer',
 'encode_promoter',
 '1bp_del',
 '1bp_ins',
 '2_5bp_del',
 '2_5bp_ins',
 'gt_5bp_del',
 'gt_5bp_ins',
 'is_indel_is_na',
 'is_insertion_is_na',
 'is_deletion_is_na',
 'encode_pls_is_na',
 'encode_pels_is_na',
 'encode_dels_is_na',
 'encode_ca_is_na',
 'encode_tf_is_na',
 'not_annotated_in_encode_is_na',
 'revel_score_is_na',
 'clinpred_score_is_na',
 'bayes_del_is_na',
 'popeve_is_na',
 'mobi_full_disorder_priority_is_na',
 'mobi_curated_disorder_priority_is_na',
 'mobi_full_lip_priority_is_na',
 'ted_domain_is_na',
 'low_complexity_domain_is_na',
 'loftee_hc_is_na',
 'loftee_lc_is_na',
 'plddt',
 'is_pioneer_interface_high',
 'clinical_significance',
 'clinvar_patho',
 'clinvar_likely_patho',
 'clinvar_benign',
 'clinvar_likely_benign']

In [13]:
annotation_dir = "/s/project/ukbbgym/annotation_files/clinvar"
cv_labels = pl.read_parquet(f"{annotation_dir}/clinvar_labels_20260621.parquet")
cv_labels

shape: (1_598_904, 2)
┌─────────────────────┬───────────────────────┐
│ id                  ┆ clinical_significance │
│ ---                 ┆ ---                   │
│ str                 ┆ str                   │
╞═════════════════════╪═══════════════════════╡
│ chr6:161360200:G:A  ┆ Likely_benign         │
│ chr21:44287497:C:T  ┆ Likely_benign         │
│ chr17:67911214:A:G  ┆ Likely_benign         │
│ chr17:1676275:G:A   ┆ Likely_benign         │
│ chr11:6640711:A:G   ┆ Likely_benign         │
│ …                   ┆ …                     │
│ chr19:39499413:C:G  ┆ Likely_benign         │
│ chr19:17787812:C:T  ┆ Likely_benign         │
│ chr3:184355543:G:C  ┆ Likely_benign         │
│ chr22:40679519:C:T  ┆ Likely_benign         │
│ chr12:132657253:C:T ┆ Likely_benign         │
└─────────────────────┴───────────────────────┘

In [14]:
cv_all_labs = (
    cv_labels
    .join(
        cv_all,
        on="id",
        # how="left",
        validate="1:m"
    )
)

cv_all_labs

shape: (1_859_698, 231)
┌────────────┬────────────┬───────┬───────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id         ┆ clinical_s ┆ chrom ┆ pos       ┆ … ┆ clinvar_pa ┆ clinvar_l ┆ clinvar_b ┆ clinvar_l │
│ ---        ┆ ignificanc ┆ ---   ┆ ---       ┆   ┆ tho        ┆ ikely_pat ┆ enign     ┆ ikely_ben │
│ str        ┆ e          ┆ str   ┆ i64       ┆   ┆ ---        ┆ ho        ┆ ---       ┆ ign       │
│            ┆ ---        ┆       ┆           ┆   ┆ i8         ┆ ---       ┆ i8        ┆ ---       │
│            ┆ str        ┆       ┆           ┆   ┆            ┆ i8        ┆           ┆ i8        │
╞════════════╪════════════╪═══════╪═══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ chr4:10268 ┆ Likely_ben ┆ chr4  ┆ 102689649 ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1         │
│ 9649:A:G   ┆ ign        ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ chr4:10268 ┆ Pathogenic ┆ chr4  ┆ 102689661 ┆ … ┆ 1          ┆ 0         ┆ 0         ┆ 0         │
│ 9661:C:T   ┆            ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ chr4:10269 ┆ Benign     ┆ chr4  ┆ 102690583 ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 0583:T:G   ┆            ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ chr4:10269 ┆ Likely_ben ┆ chr4  ┆ 102690671 ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1         │
│ 0671:C:T   ┆ ign        ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ chr4:10269 ┆ Likely_ben ┆ chr4  ┆ 102690674 ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1         │
│ 0674:C:T   ┆ ign        ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …          ┆ …     ┆ …         ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ chr5:14064 ┆ Likely_ben ┆ chr5  ┆ 140647688 ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1         │
│ 7688:GC:G  ┆ ign        ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ chr2:43912 ┆ Likely_pat ┆ chr2  ┆ 43912558  ┆ … ┆ 0          ┆ 1         ┆ 0         ┆ 0         │
│ 558:CCT:C  ┆ hogenic    ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ chr11:1256 ┆ Benign     ┆ chr11 ┆ 125602442 ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 02442:G:GT ┆            ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ chr10:5382 ┆ Likely_ben ┆ chr10 ┆ 53822445  ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1         │
│ 2445:CAGGA ┆ ign        ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ GG:C       ┆            ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
│ chr17:7673 ┆ Likely_ben ┆ chr17 ┆ 7673346   ┆ … ┆ 0          ┆ 0         ┆ 0         ┆ 1         │
│ 346:AAT:A  ┆ ign        ┆       ┆           ┆   ┆            ┆           ┆           ┆           │
└────────────┴────────────┴───────┴───────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [15]:
cv_all_labs.write_parquet(
    f"{annotation_dir}/clinvar_significance_vep_annotations_processed_cadd_fill_na_20260621.parquet"
)